// Code generated by ent, DO NOT EDIT.

package balancesnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the balancesnapshot type in the database.
	Label = "balance_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPeriod holds the string denoting the period field in the database.
	FieldPeriod = "period"
	// FieldOpeningBalance holds the string denoting the opening_balance field in the database.
	FieldOpeningBalance = "opening_balance"
	// FieldClosingBalance holds the string denoting the closing_balance field in the database.
	FieldClosingBalance = "closing_balance"
	// FieldDepositTotal holds the string denoting the deposit_total field in the database.
	FieldDepositTotal = "deposit_total"
	// FieldWithdrawTotal holds the string denoting the withdraw_total field in the database.
	FieldWithdrawTotal = "withdraw_total"
	// FieldCreditTotal holds the string denoting the credit_total field in the database.
	FieldCreditTotal = "credit_total"
	// FieldUtilisationGrossTotal holds the string denoting the utilisation_gross_total field in the database.
	FieldUtilisationGrossTotal = "utilisation_gross_total"
	// FieldUtilisationTotal holds the string denoting the utilisation_total field in the database.
	FieldUtilisationTotal = "utilisation_total"
	// FieldComputedAt holds the string denoting the computed_at field in the database.
	FieldComputedAt = "computed_at"
	// Table holds the table name of the balancesnapshot in the database.
	Table = "balance_snapshots"
)

// Columns holds all SQL columns for balancesnapshot fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPeriod,
	FieldOpeningBalance,
	FieldClosingBalance,
	FieldDepositTotal,
	FieldWithdrawTotal,
	FieldCreditTotal,
	FieldUtilisationGrossTotal,
	FieldUtilisationTotal,
	FieldComputedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PeriodValidator is a validator for the "period" field. It is called by the builders before save.
	PeriodValidator func(string) error
	// DefaultOpeningBalance holds the default value on creation for the "opening_balance" field.
	DefaultOpeningBalance float64
	// DefaultClosingBalance holds the default value on creation for the "closing_balance" field.
	DefaultClosingBalance float64
	// DefaultDepositTotal holds the default value on creation for the "deposit_total" field.
	DefaultDepositTotal float64
	// DefaultWithdrawTotal holds the default value on creation for the "withdraw_total" field.
	DefaultWithdrawTotal float64
	// DefaultCreditTotal holds the default value on creation for the "credit_total" field.
	DefaultCreditTotal float64
	// DefaultUtilisationGrossTotal holds the default value on creation for the "utilisation_gross_total" field.
	DefaultUtilisationGrossTotal float64
	// DefaultUtilisationTotal holds the default value on creation for the "utilisation_total" field.
	DefaultUtilisationTotal float64
	// DefaultComputedAt holds the default value on creation for the "computed_at" field.
	DefaultComputedAt func() time.Time
	// UpdateDefaultComputedAt holds the default value on update for the "computed_at" field.
	UpdateDefaultComputedAt func() time.Time
)

// OrderOption defines the ordering options for the BalanceSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPeriod orders the results by the period field.
func ByPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriod, opts...).ToFunc()
}

// ByOpeningBalance orders the results by the opening_balance field.
func ByOpeningBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpeningBalance, opts...).ToFunc()
}

// ByClosingBalance orders the results by the closing_balance field.
func ByClosingBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosingBalance, opts...).ToFunc()
}

// ByDepositTotal orders the results by the deposit_total field.
func ByDepositTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepositTotal, opts...).ToFunc()
}

// ByWithdrawTotal orders the results by the withdraw_total field.
func ByWithdrawTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWithdrawTotal, opts...).ToFunc()
}

// ByCreditTotal orders the results by the credit_total field.
func ByCreditTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditTotal, opts...).ToFunc()
}

// ByUtilisationGrossTotal orders the results by the utilisation_gross_total field.
func ByUtilisationGrossTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUtilisationGrossTotal, opts...).ToFunc()
}

// ByUtilisationTotal orders the results by the utilisation_total field.
func ByUtilisationTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUtilisationTotal, opts...).ToFunc()
}

// ByComputedAt orders the results by the computed_at field.
func ByComputedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComputedAt, opts...).ToFunc()
}
