// Code generated by ent, DO NOT EDIT.

package teamactivitylog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldLTE(FieldID, id))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEQ(FieldOwnerUserID, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEQ(FieldActorUserID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEQ(FieldAction, v))
}

// Detail applies equality check predicate on the "detail" field. It's identical to DetailEQ.
func Detail(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEQ(FieldDetail, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEQ(FieldCreatedAt, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldLTE(FieldOwnerUserID, v))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDGT applies the GT predicate on the "actor_user_id" field.
func ActorUserIDGT(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldGT(FieldActorUserID, v))
}

// ActorUserIDGTE applies the GTE predicate on the "actor_user_id" field.
func ActorUserIDGTE(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldGTE(FieldActorUserID, v))
}

// ActorUserIDLT applies the LT predicate on the "actor_user_id" field.
func ActorUserIDLT(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldLT(FieldActorUserID, v))
}

// ActorUserIDLTE applies the LTE predicate on the "actor_user_id" field.
func ActorUserIDLTE(v int64) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldLTE(FieldActorUserID, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldContainsFold(FieldAction, v))
}

// DetailEQ applies the EQ predicate on the "detail" field.
func DetailEQ(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEQ(FieldDetail, v))
}

// DetailNEQ applies the NEQ predicate on the "detail" field.
func DetailNEQ(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldNEQ(FieldDetail, v))
}

// DetailIn applies the In predicate on the "detail" field.
func DetailIn(vs ...string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldIn(FieldDetail, vs...))
}

// DetailNotIn applies the NotIn predicate on the "detail" field.
func DetailNotIn(vs ...string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldNotIn(FieldDetail, vs...))
}

// DetailGT applies the GT predicate on the "detail" field.
func DetailGT(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldGT(FieldDetail, v))
}

// DetailGTE applies the GTE predicate on the "detail" field.
func DetailGTE(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldGTE(FieldDetail, v))
}

// DetailLT applies the LT predicate on the "detail" field.
func DetailLT(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldLT(FieldDetail, v))
}

// DetailLTE applies the LTE predicate on the "detail" field.
func DetailLTE(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldLTE(FieldDetail, v))
}

// DetailContains applies the Contains predicate on the "detail" field.
func DetailContains(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldContains(FieldDetail, v))
}

// DetailHasPrefix applies the HasPrefix predicate on the "detail" field.
func DetailHasPrefix(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldHasPrefix(FieldDetail, v))
}

// DetailHasSuffix applies the HasSuffix predicate on the "detail" field.
func DetailHasSuffix(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldHasSuffix(FieldDetail, v))
}

// DetailEqualFold applies the EqualFold predicate on the "detail" field.
func DetailEqualFold(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEqualFold(FieldDetail, v))
}

// DetailContainsFold applies the ContainsFold predicate on the "detail" field.
func DetailContainsFold(v string) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldContainsFold(FieldDetail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamActivityLog) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamActivityLog) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamActivityLog) predicate.TeamActivityLog {
	return predicate.TeamActivityLog(sql.NotPredicates(p))
}
