// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancesnapshot"
)

// BalanceSnapshotCreate is the builder for creating a BalanceSnapshot entity.
type BalanceSnapshotCreate struct {
	config
	mutation *BalanceSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *BalanceSnapshotCreate) SetUserID(v int64) *BalanceSnapshotCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPeriod sets the "period" field.
func (_c *BalanceSnapshotCreate) SetPeriod(v string) *BalanceSnapshotCreate {
	_c.mutation.SetPeriod(v)
	return _c
}

// SetOpeningBalance sets the "opening_balance" field.
func (_c *BalanceSnapshotCreate) SetOpeningBalance(v float64) *BalanceSnapshotCreate {
	_c.mutation.SetOpeningBalance(v)
	return _c
}

// SetNillableOpeningBalance sets the "opening_balance" field if the given value is not nil.
func (_c *BalanceSnapshotCreate) SetNillableOpeningBalance(v *float64) *BalanceSnapshotCreate {
	if v != nil {
		_c.SetOpeningBalance(*v)
	}
	return _c
}

// SetClosingBalance sets the "closing_balance" field.
func (_c *BalanceSnapshotCreate) SetClosingBalance(v float64) *BalanceSnapshotCreate {
	_c.mutation.SetClosingBalance(v)
	return _c
}

// SetNillableClosingBalance sets the "closing_balance" field if the given value is not nil.
func (_c *BalanceSnapshotCreate) SetNillableClosingBalance(v *float64) *BalanceSnapshotCreate {
	if v != nil {
		_c.SetClosingBalance(*v)
	}
	return _c
}

// SetDepositTotal sets the "deposit_total" field.
func (_c *BalanceSnapshotCreate) SetDepositTotal(v float64) *BalanceSnapshotCreate {
	_c.mutation.SetDepositTotal(v)
	return _c
}

// SetNillableDepositTotal sets the "deposit_total" field if the given value is not nil.
func (_c *BalanceSnapshotCreate) SetNillableDepositTotal(v *float64) *BalanceSnapshotCreate {
	if v != nil {
		_c.SetDepositTotal(*v)
	}
	return _c
}

// SetWithdrawTotal sets the "withdraw_total" field.
func (_c *BalanceSnapshotCreate) SetWithdrawTotal(v float64) *BalanceSnapshotCreate {
	_c.mutation.SetWithdrawTotal(v)
	return _c
}

// SetNillableWithdrawTotal sets the "withdraw_total" field if the given value is not nil.
func (_c *BalanceSnapshotCreate) SetNillableWithdrawTotal(v *float64) *BalanceSnapshotCreate {
	if v != nil {
		_c.SetWithdrawTotal(*v)
	}
	return _c
}

// SetCreditTotal sets the "credit_total" field.
func (_c *BalanceSnapshotCreate) SetCreditTotal(v float64) *BalanceSnapshotCreate {
	_c.mutation.SetCreditTotal(v)
	return _c
}

// SetNillableCreditTotal sets the "credit_total" field if the given value is not nil.
func (_c *BalanceSnapshotCreate) SetNillableCreditTotal(v *float64) *BalanceSnapshotCreate {
	if v != nil {
		_c.SetCreditTotal(*v)
	}
	return _c
}

// SetUtilisationGrossTotal sets the "utilisation_gross_total" field.
func (_c *BalanceSnapshotCreate) SetUtilisationGrossTotal(v float64) *BalanceSnapshotCreate {
	_c.mutation.SetUtilisationGrossTotal(v)
	return _c
}

// SetNillableUtilisationGrossTotal sets the "utilisation_gross_total" field if the given value is not nil.
func (_c *BalanceSnapshotCreate) SetNillableUtilisationGrossTotal(v *float64) *BalanceSnapshotCreate {
	if v != nil {
		_c.SetUtilisationGrossTotal(*v)
	}
	return _c
}

// SetUtilisationTotal sets the "utilisation_total" field.
func (_c *BalanceSnapshotCreate) SetUtilisationTotal(v float64) *BalanceSnapshotCreate {
	_c.mutation.SetUtilisationTotal(v)
	return _c
}

// SetNillableUtilisationTotal sets the "utilisation_total" field if the given value is not nil.
func (_c *BalanceSnapshotCreate) SetNillableUtilisationTotal(v *float64) *BalanceSnapshotCreate {
	if v != nil {
		_c.SetUtilisationTotal(*v)
	}
	return _c
}

// SetComputedAt sets the "computed_at" field.
func (_c *BalanceSnapshotCreate) SetComputedAt(v time.Time) *BalanceSnapshotCreate {
	_c.mutation.SetComputedAt(v)
	return _c
}

// SetNillableComputedAt sets the "computed_at" field if the given value is not nil.
func (_c *BalanceSnapshotCreate) SetNillableComputedAt(v *time.Time) *BalanceSnapshotCreate {
	if v != nil {
		_c.SetComputedAt(*v)
	}
	return _c
}

// Mutation returns the BalanceSnapshotMutation object of the builder.
func (_c *BalanceSnapshotCreate) Mutation() *BalanceSnapshotMutation {
	return _c.mutation
}

// Save creates the BalanceSnapshot in the database.
func (_c *BalanceSnapshotCreate) Save(ctx context.Context) (*BalanceSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BalanceSnapshotCreate) SaveX(ctx context.Context) *BalanceSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BalanceSnapshotCreate) defaults() {
	if _, ok := _c.mutation.OpeningBalance(); !ok {
		v := balancesnapshot.DefaultOpeningBalance
		_c.mutation.SetOpeningBalance(v)
	}
	if _, ok := _c.mutation.ClosingBalance(); !ok {
		v := balancesnapshot.DefaultClosingBalance
		_c.mutation.SetClosingBalance(v)
	}
	if _, ok := _c.mutation.DepositTotal(); !ok {
		v := balancesnapshot.DefaultDepositTotal
		_c.mutation.SetDepositTotal(v)
	}
	if _, ok := _c.mutation.WithdrawTotal(); !ok {
		v := balancesnapshot.DefaultWithdrawTotal
		_c.mutation.SetWithdrawTotal(v)
	}
	if _, ok := _c.mutation.CreditTotal(); !ok {
		v := balancesnapshot.DefaultCreditTotal
		_c.mutation.SetCreditTotal(v)
	}
	if _, ok := _c.mutation.UtilisationGrossTotal(); !ok {
		v := balancesnapshot.DefaultUtilisationGrossTotal
		_c.mutation.SetUtilisationGrossTotal(v)
	}
	if _, ok := _c.mutation.UtilisationTotal(); !ok {
		v := balancesnapshot.DefaultUtilisationTotal
		_c.mutation.SetUtilisationTotal(v)
	}
	if _, ok := _c.mutation.ComputedAt(); !ok {
		v := balancesnapshot.DefaultComputedAt()
		_c.mutation.SetComputedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BalanceSnapshotCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BalanceSnapshot.user_id"`)}
	}
	if _, ok := _c.mutation.Period(); !ok {
		return &ValidationError{Name: "period", err: errors.New(`ent: missing required field "BalanceSnapshot.period"`)}
	}
	if v, ok := _c.mutation.Period(); ok {
		if err := balancesnapshot.PeriodValidator(v); err != nil {
			return &ValidationError{Name: "period", err: fmt.Errorf(`ent: validator failed for field "BalanceSnapshot.period": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OpeningBalance(); !ok {
		return &ValidationError{Name: "opening_balance", err: errors.New(`ent: missing required field "BalanceSnapshot.opening_balance"`)}
	}
	if _, ok := _c.mutation.ClosingBalance(); !ok {
		return &ValidationError{Name: "closing_balance", err: errors.New(`ent: missing required field "BalanceSnapshot.closing_balance"`)}
	}
	if _, ok := _c.mutation.DepositTotal(); !ok {
		return &ValidationError{Name: "deposit_total", err: errors.New(`ent: missing required field "BalanceSnapshot.deposit_total"`)}
	}
	if _, ok := _c.mutation.WithdrawTotal(); !ok {
		return &ValidationError{Name: "withdraw_total", err: errors.New(`ent: missing required field "BalanceSnapshot.withdraw_total"`)}
	}
	if _, ok := _c.mutation.CreditTotal(); !ok {
		return &ValidationError{Name: "credit_total", err: errors.New(`ent: missing required field "BalanceSnapshot.credit_total"`)}
	}
	if _, ok := _c.mutation.UtilisationGrossTotal(); !ok {
		return &ValidationError{Name: "utilisation_gross_total", err: errors.New(`ent: missing required field "BalanceSnapshot.utilisation_gross_total"`)}
	}
	if _, ok := _c.mutation.UtilisationTotal(); !ok {
		return &ValidationError{Name: "utilisation_total", err: errors.New(`ent: missing required field "BalanceSnapshot.utilisation_total"`)}
	}
	if _, ok := _c.mutation.ComputedAt(); !ok {
		return &ValidationError{Name: "computed_at", err: errors.New(`ent: missing required field "BalanceSnapshot.computed_at"`)}
	}
	return nil
}

func (_c *BalanceSnapshotCreate) sqlSave(ctx context.Context) (*BalanceSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BalanceSnapshotCreate) createSpec() (*BalanceSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &BalanceSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(balancesnapshot.Table, sqlgraph.NewFieldSpec(balancesnapshot.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(balancesnapshot.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Period(); ok {
		_spec.SetField(balancesnapshot.FieldPeriod, field.TypeString, value)
		_node.Period = value
	}
	if value, ok := _c.mutation.OpeningBalance(); ok {
		_spec.SetField(balancesnapshot.FieldOpeningBalance, field.TypeFloat64, value)
		_node.OpeningBalance = value
	}
	if value, ok := _c.mutation.ClosingBalance(); ok {
		_spec.SetField(balancesnapshot.FieldClosingBalance, field.TypeFloat64, value)
		_node.ClosingBalance = value
	}
	if value, ok := _c.mutation.DepositTotal(); ok {
		_spec.SetField(balancesnapshot.FieldDepositTotal, field.TypeFloat64, value)
		_node.DepositTotal = value
	}
	if value, ok := _c.mutation.WithdrawTotal(); ok {
		_spec.SetField(balancesnapshot.FieldWithdrawTotal, field.TypeFloat64, value)
		_node.WithdrawTotal = value
	}
	if value, ok := _c.mutation.CreditTotal(); ok {
		_spec.SetField(balancesnapshot.FieldCreditTotal, field.TypeFloat64, value)
		_node.CreditTotal = value
	}
	if value, ok := _c.mutation.UtilisationGrossTotal(); ok {
		_spec.SetField(balancesnapshot.FieldUtilisationGrossTotal, field.TypeFloat64, value)
		_node.UtilisationGrossTotal = value
	}
	if value, ok := _c.mutation.UtilisationTotal(); ok {
		_spec.SetField(balancesnapshot.FieldUtilisationTotal, field.TypeFloat64, value)
		_node.UtilisationTotal = value
	}
	if value, ok := _c.mutation.ComputedAt(); ok {
		_spec.SetField(balancesnapshot.FieldComputedAt, field.TypeTime, value)
		_node.ComputedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceSnapshot.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceSnapshotUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *BalanceSnapshotUpsertOne {
	_c.conflict = opts
	return &BalanceSnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceSnapshotCreate) OnConflictColumns(columns ...string) *BalanceSnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceSnapshotUpsertOne{
		create: _c,
	}
}

type (
	// BalanceSnapshotUpsertOne is the builder for "upsert"-ing
	//  one BalanceSnapshot node.
	BalanceSnapshotUpsertOne struct {
		create *BalanceSnapshotCreate
	}

	// BalanceSnapshotUpsert is the "OnConflict" setter.
	BalanceSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *BalanceSnapshotUpsert) SetUserID(v int64) *BalanceSnapshotUpsert {
	u.Set(balancesnapshot.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceSnapshotUpsert) UpdateUserID() *BalanceSnapshotUpsert {
	u.SetExcluded(balancesnapshot.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceSnapshotUpsert) AddUserID(v int64) *BalanceSnapshotUpsert {
	u.Add(balancesnapshot.FieldUserID, v)
	return u
}

// SetPeriod sets the "period" field.
func (u *BalanceSnapshotUpsert) SetPeriod(v string) *BalanceSnapshotUpsert {
	u.Set(balancesnapshot.FieldPeriod, v)
	return u
}

// UpdatePeriod sets the "period" field to the value that was provided on create.
func (u *BalanceSnapshotUpsert) UpdatePeriod() *BalanceSnapshotUpsert {
	u.SetExcluded(balancesnapshot.FieldPeriod)
	return u
}

// SetOpeningBalance sets the "opening_balance" field.
func (u *BalanceSnapshotUpsert) SetOpeningBalance(v float64) *BalanceSnapshotUpsert {
	u.Set(balancesnapshot.FieldOpeningBalance, v)
	return u
}

// UpdateOpeningBalance sets the "opening_balance" field to the value that was provided on create.
func (u *BalanceSnapshotUpsert) UpdateOpeningBalance() *BalanceSnapshotUpsert {
	u.SetExcluded(balancesnapshot.FieldOpeningBalance)
	return u
}

// AddOpeningBalance adds v to the "opening_balance" field.
func (u *BalanceSnapshotUpsert) AddOpeningBalance(v float64) *BalanceSnapshotUpsert {
	u.Add(balancesnapshot.FieldOpeningBalance, v)
	return u
}

// SetClosingBalance sets the "closing_balance" field.
func (u *BalanceSnapshotUpsert) SetClosingBalance(v float64) *BalanceSnapshotUpsert {
	u.Set(balancesnapshot.FieldClosingBalance, v)
	return u
}

// UpdateClosingBalance sets the "closing_balance" field to the value that was provided on create.
func (u *BalanceSnapshotUpsert) UpdateClosingBalance() *BalanceSnapshotUpsert {
	u.SetExcluded(balancesnapshot.FieldClosingBalance)
	return u
}

// AddClosingBalance adds v to the "closing_balance" field.
func (u *BalanceSnapshotUpsert) AddClosingBalance(v float64) *BalanceSnapshotUpsert {
	u.Add(balancesnapshot.FieldClosingBalance, v)
	return u
}

// SetDepositTotal sets the "deposit_total" field.
func (u *BalanceSnapshotUpsert) SetDepositTotal(v float64) *BalanceSnapshotUpsert {
	u.Set(balancesnapshot.FieldDepositTotal, v)
	return u
}

// UpdateDepositTotal sets the "deposit_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsert) UpdateDepositTotal() *BalanceSnapshotUpsert {
	u.SetExcluded(balancesnapshot.FieldDepositTotal)
	return u
}

// AddDepositTotal adds v to the "deposit_total" field.
func (u *BalanceSnapshotUpsert) AddDepositTotal(v float64) *BalanceSnapshotUpsert {
	u.Add(balancesnapshot.FieldDepositTotal, v)
	return u
}

// SetWithdrawTotal sets the "withdraw_total" field.
func (u *BalanceSnapshotUpsert) SetWithdrawTotal(v float64) *BalanceSnapshotUpsert {
	u.Set(balancesnapshot.FieldWithdrawTotal, v)
	return u
}

// UpdateWithdrawTotal sets the "withdraw_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsert) UpdateWithdrawTotal() *BalanceSnapshotUpsert {
	u.SetExcluded(balancesnapshot.FieldWithdrawTotal)
	return u
}

// AddWithdrawTotal adds v to the "withdraw_total" field.
func (u *BalanceSnapshotUpsert) AddWithdrawTotal(v float64) *BalanceSnapshotUpsert {
	u.Add(balancesnapshot.FieldWithdrawTotal, v)
	return u
}

// SetCreditTotal sets the "credit_total" field.
func (u *BalanceSnapshotUpsert) SetCreditTotal(v float64) *BalanceSnapshotUpsert {
	u.Set(balancesnapshot.FieldCreditTotal, v)
	return u
}

// UpdateCreditTotal sets the "credit_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsert) UpdateCreditTotal() *BalanceSnapshotUpsert {
	u.SetExcluded(balancesnapshot.FieldCreditTotal)
	return u
}

// AddCreditTotal adds v to the "credit_total" field.
func (u *BalanceSnapshotUpsert) AddCreditTotal(v float64) *BalanceSnapshotUpsert {
	u.Add(balancesnapshot.FieldCreditTotal, v)
	return u
}

// SetUtilisationGrossTotal sets the "utilisation_gross_total" field.
func (u *BalanceSnapshotUpsert) SetUtilisationGrossTotal(v float64) *BalanceSnapshotUpsert {
	u.Set(balancesnapshot.FieldUtilisationGrossTotal, v)
	return u
}

// UpdateUtilisationGrossTotal sets the "utilisation_gross_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsert) UpdateUtilisationGrossTotal() *BalanceSnapshotUpsert {
	u.SetExcluded(balancesnapshot.FieldUtilisationGrossTotal)
	return u
}

// AddUtilisationGrossTotal adds v to the "utilisation_gross_total" field.
func (u *BalanceSnapshotUpsert) AddUtilisationGrossTotal(v float64) *BalanceSnapshotUpsert {
	u.Add(balancesnapshot.FieldUtilisationGrossTotal, v)
	return u
}

// SetUtilisationTotal sets the "utilisation_total" field.
func (u *BalanceSnapshotUpsert) SetUtilisationTotal(v float64) *BalanceSnapshotUpsert {
	u.Set(balancesnapshot.FieldUtilisationTotal, v)
	return u
}

// UpdateUtilisationTotal sets the "utilisation_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsert) UpdateUtilisationTotal() *BalanceSnapshotUpsert {
	u.SetExcluded(balancesnapshot.FieldUtilisationTotal)
	return u
}

// AddUtilisationTotal adds v to the "utilisation_total" field.
func (u *BalanceSnapshotUpsert) AddUtilisationTotal(v float64) *BalanceSnapshotUpsert {
	u.Add(balancesnapshot.FieldUtilisationTotal, v)
	return u
}

// SetComputedAt sets the "computed_at" field.
func (u *BalanceSnapshotUpsert) SetComputedAt(v time.Time) *BalanceSnapshotUpsert {
	u.Set(balancesnapshot.FieldComputedAt, v)
	return u
}

// UpdateComputedAt sets the "computed_at" field to the value that was provided on create.
func (u *BalanceSnapshotUpsert) UpdateComputedAt() *BalanceSnapshotUpsert {
	u.SetExcluded(balancesnapshot.FieldComputedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BalanceSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceSnapshotUpsertOne) UpdateNewValues() *BalanceSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BalanceSnapshotUpsertOne) Ignore() *BalanceSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceSnapshotUpsertOne) DoNothing() *BalanceSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceSnapshotCreate.OnConflict
// documentation for more info.
func (u *BalanceSnapshotUpsertOne) Update(set func(*BalanceSnapshotUpsert)) *BalanceSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *BalanceSnapshotUpsertOne) SetUserID(v int64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceSnapshotUpsertOne) AddUserID(v int64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertOne) UpdateUserID() *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateUserID()
	})
}

// SetPeriod sets the "period" field.
func (u *BalanceSnapshotUpsertOne) SetPeriod(v string) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetPeriod(v)
	})
}

// UpdatePeriod sets the "period" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertOne) UpdatePeriod() *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdatePeriod()
	})
}

// SetOpeningBalance sets the "opening_balance" field.
func (u *BalanceSnapshotUpsertOne) SetOpeningBalance(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetOpeningBalance(v)
	})
}

// AddOpeningBalance adds v to the "opening_balance" field.
func (u *BalanceSnapshotUpsertOne) AddOpeningBalance(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddOpeningBalance(v)
	})
}

// UpdateOpeningBalance sets the "opening_balance" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertOne) UpdateOpeningBalance() *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateOpeningBalance()
	})
}

// SetClosingBalance sets the "closing_balance" field.
func (u *BalanceSnapshotUpsertOne) SetClosingBalance(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetClosingBalance(v)
	})
}

// AddClosingBalance adds v to the "closing_balance" field.
func (u *BalanceSnapshotUpsertOne) AddClosingBalance(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddClosingBalance(v)
	})
}

// UpdateClosingBalance sets the "closing_balance" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertOne) UpdateClosingBalance() *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateClosingBalance()
	})
}

// SetDepositTotal sets the "deposit_total" field.
func (u *BalanceSnapshotUpsertOne) SetDepositTotal(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetDepositTotal(v)
	})
}

// AddDepositTotal adds v to the "deposit_total" field.
func (u *BalanceSnapshotUpsertOne) AddDepositTotal(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddDepositTotal(v)
	})
}

// UpdateDepositTotal sets the "deposit_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertOne) UpdateDepositTotal() *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateDepositTotal()
	})
}

// SetWithdrawTotal sets the "withdraw_total" field.
func (u *BalanceSnapshotUpsertOne) SetWithdrawTotal(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetWithdrawTotal(v)
	})
}

// AddWithdrawTotal adds v to the "withdraw_total" field.
func (u *BalanceSnapshotUpsertOne) AddWithdrawTotal(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddWithdrawTotal(v)
	})
}

// UpdateWithdrawTotal sets the "withdraw_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertOne) UpdateWithdrawTotal() *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateWithdrawTotal()
	})
}

// SetCreditTotal sets the "credit_total" field.
func (u *BalanceSnapshotUpsertOne) SetCreditTotal(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetCreditTotal(v)
	})
}

// AddCreditTotal adds v to the "credit_total" field.
func (u *BalanceSnapshotUpsertOne) AddCreditTotal(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddCreditTotal(v)
	})
}

// UpdateCreditTotal sets the "credit_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertOne) UpdateCreditTotal() *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateCreditTotal()
	})
}

// SetUtilisationGrossTotal sets the "utilisation_gross_total" field.
func (u *BalanceSnapshotUpsertOne) SetUtilisationGrossTotal(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetUtilisationGrossTotal(v)
	})
}

// AddUtilisationGrossTotal adds v to the "utilisation_gross_total" field.
func (u *BalanceSnapshotUpsertOne) AddUtilisationGrossTotal(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddUtilisationGrossTotal(v)
	})
}

// UpdateUtilisationGrossTotal sets the "utilisation_gross_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertOne) UpdateUtilisationGrossTotal() *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateUtilisationGrossTotal()
	})
}

// SetUtilisationTotal sets the "utilisation_total" field.
func (u *BalanceSnapshotUpsertOne) SetUtilisationTotal(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetUtilisationTotal(v)
	})
}

// AddUtilisationTotal adds v to the "utilisation_total" field.
func (u *BalanceSnapshotUpsertOne) AddUtilisationTotal(v float64) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddUtilisationTotal(v)
	})
}

// UpdateUtilisationTotal sets the "utilisation_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertOne) UpdateUtilisationTotal() *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateUtilisationTotal()
	})
}

// SetComputedAt sets the "computed_at" field.
func (u *BalanceSnapshotUpsertOne) SetComputedAt(v time.Time) *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetComputedAt(v)
	})
}

// UpdateComputedAt sets the "computed_at" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertOne) UpdateComputedAt() *BalanceSnapshotUpsertOne {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateComputedAt()
	})
}

// Exec executes the query.
func (u *BalanceSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BalanceSnapshotUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BalanceSnapshotUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BalanceSnapshotCreateBulk is the builder for creating many BalanceSnapshot entities in bulk.
type BalanceSnapshotCreateBulk struct {
	config
	err      error
	builders []*BalanceSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the BalanceSnapshot entities in the database.
func (_c *BalanceSnapshotCreateBulk) Save(ctx context.Context) ([]*BalanceSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BalanceSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BalanceSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BalanceSnapshotCreateBulk) SaveX(ctx context.Context) []*BalanceSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceSnapshotUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *BalanceSnapshotUpsertBulk {
	_c.conflict = opts
	return &BalanceSnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceSnapshotCreateBulk) OnConflictColumns(columns ...string) *BalanceSnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceSnapshotUpsertBulk{
		create: _c,
	}
}

// BalanceSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of BalanceSnapshot nodes.
type BalanceSnapshotUpsertBulk struct {
	create *BalanceSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BalanceSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceSnapshotUpsertBulk) UpdateNewValues() *BalanceSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BalanceSnapshotUpsertBulk) Ignore() *BalanceSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceSnapshotUpsertBulk) DoNothing() *BalanceSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *BalanceSnapshotUpsertBulk) Update(set func(*BalanceSnapshotUpsert)) *BalanceSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *BalanceSnapshotUpsertBulk) SetUserID(v int64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceSnapshotUpsertBulk) AddUserID(v int64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertBulk) UpdateUserID() *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateUserID()
	})
}

// SetPeriod sets the "period" field.
func (u *BalanceSnapshotUpsertBulk) SetPeriod(v string) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetPeriod(v)
	})
}

// UpdatePeriod sets the "period" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertBulk) UpdatePeriod() *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdatePeriod()
	})
}

// SetOpeningBalance sets the "opening_balance" field.
func (u *BalanceSnapshotUpsertBulk) SetOpeningBalance(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetOpeningBalance(v)
	})
}

// AddOpeningBalance adds v to the "opening_balance" field.
func (u *BalanceSnapshotUpsertBulk) AddOpeningBalance(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddOpeningBalance(v)
	})
}

// UpdateOpeningBalance sets the "opening_balance" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertBulk) UpdateOpeningBalance() *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateOpeningBalance()
	})
}

// SetClosingBalance sets the "closing_balance" field.
func (u *BalanceSnapshotUpsertBulk) SetClosingBalance(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetClosingBalance(v)
	})
}

// AddClosingBalance adds v to the "closing_balance" field.
func (u *BalanceSnapshotUpsertBulk) AddClosingBalance(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddClosingBalance(v)
	})
}

// UpdateClosingBalance sets the "closing_balance" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertBulk) UpdateClosingBalance() *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateClosingBalance()
	})
}

// SetDepositTotal sets the "deposit_total" field.
func (u *BalanceSnapshotUpsertBulk) SetDepositTotal(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetDepositTotal(v)
	})
}

// AddDepositTotal adds v to the "deposit_total" field.
func (u *BalanceSnapshotUpsertBulk) AddDepositTotal(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddDepositTotal(v)
	})
}

// UpdateDepositTotal sets the "deposit_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertBulk) UpdateDepositTotal() *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateDepositTotal()
	})
}

// SetWithdrawTotal sets the "withdraw_total" field.
func (u *BalanceSnapshotUpsertBulk) SetWithdrawTotal(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetWithdrawTotal(v)
	})
}

// AddWithdrawTotal adds v to the "withdraw_total" field.
func (u *BalanceSnapshotUpsertBulk) AddWithdrawTotal(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddWithdrawTotal(v)
	})
}

// UpdateWithdrawTotal sets the "withdraw_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertBulk) UpdateWithdrawTotal() *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateWithdrawTotal()
	})
}

// SetCreditTotal sets the "credit_total" field.
func (u *BalanceSnapshotUpsertBulk) SetCreditTotal(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetCreditTotal(v)
	})
}

// AddCreditTotal adds v to the "credit_total" field.
func (u *BalanceSnapshotUpsertBulk) AddCreditTotal(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddCreditTotal(v)
	})
}

// UpdateCreditTotal sets the "credit_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertBulk) UpdateCreditTotal() *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateCreditTotal()
	})
}

// SetUtilisationGrossTotal sets the "utilisation_gross_total" field.
func (u *BalanceSnapshotUpsertBulk) SetUtilisationGrossTotal(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetUtilisationGrossTotal(v)
	})
}

// AddUtilisationGrossTotal adds v to the "utilisation_gross_total" field.
func (u *BalanceSnapshotUpsertBulk) AddUtilisationGrossTotal(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddUtilisationGrossTotal(v)
	})
}

// UpdateUtilisationGrossTotal sets the "utilisation_gross_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertBulk) UpdateUtilisationGrossTotal() *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateUtilisationGrossTotal()
	})
}

// SetUtilisationTotal sets the "utilisation_total" field.
func (u *BalanceSnapshotUpsertBulk) SetUtilisationTotal(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetUtilisationTotal(v)
	})
}

// AddUtilisationTotal adds v to the "utilisation_total" field.
func (u *BalanceSnapshotUpsertBulk) AddUtilisationTotal(v float64) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.AddUtilisationTotal(v)
	})
}

// UpdateUtilisationTotal sets the "utilisation_total" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertBulk) UpdateUtilisationTotal() *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateUtilisationTotal()
	})
}

// SetComputedAt sets the "computed_at" field.
func (u *BalanceSnapshotUpsertBulk) SetComputedAt(v time.Time) *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.SetComputedAt(v)
	})
}

// UpdateComputedAt sets the "computed_at" field to the value that was provided on create.
func (u *BalanceSnapshotUpsertBulk) UpdateComputedAt() *BalanceSnapshotUpsertBulk {
	return u.Update(func(s *BalanceSnapshotUpsert) {
		s.UpdateComputedAt()
	})
}

// Exec executes the query.
func (u *BalanceSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BalanceSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
