// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/balancesnapshot"
)

// BalanceSnapshot is the model entity for the BalanceSnapshot schema.
type BalanceSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Period holds the value of the "period" field.
	Period string `json:"period,omitempty"`
	// OpeningBalance holds the value of the "opening_balance" field.
	OpeningBalance float64 `json:"opening_balance,omitempty"`
	// ClosingBalance holds the value of the "closing_balance" field.
	ClosingBalance float64 `json:"closing_balance,omitempty"`
	// DepositTotal holds the value of the "deposit_total" field.
	DepositTotal float64 `json:"deposit_total,omitempty"`
	// WithdrawTotal holds the value of the "withdraw_total" field.
	WithdrawTotal float64 `json:"withdraw_total,omitempty"`
	// CreditTotal holds the value of the "credit_total" field.
	CreditTotal float64 `json:"credit_total,omitempty"`
	// UtilisationGrossTotal holds the value of the "utilisation_gross_total" field.
	UtilisationGrossTotal float64 `json:"utilisation_gross_total,omitempty"`
	// UtilisationTotal holds the value of the "utilisation_total" field.
	UtilisationTotal float64 `json:"utilisation_total,omitempty"`
	// ComputedAt holds the value of the "computed_at" field.
	ComputedAt   time.Time `json:"computed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BalanceSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case balancesnapshot.FieldOpeningBalance, balancesnapshot.FieldClosingBalance, balancesnapshot.FieldDepositTotal, balancesnapshot.FieldWithdrawTotal, balancesnapshot.FieldCreditTotal, balancesnapshot.FieldUtilisationGrossTotal, balancesnapshot.FieldUtilisationTotal:
			values[i] = new(sql.NullFloat64)
		case balancesnapshot.FieldID, balancesnapshot.FieldUserID:
			values[i] = new(sql.NullInt64)
		case balancesnapshot.FieldPeriod:
			values[i] = new(sql.NullString)
		case balancesnapshot.FieldComputedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BalanceSnapshot fields.
func (_m *BalanceSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case balancesnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case balancesnapshot.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case balancesnapshot.FieldPeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field period", values[i])
			} else if value.Valid {
				_m.Period = value.String
			}
		case balancesnapshot.FieldOpeningBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field opening_balance", values[i])
			} else if value.Valid {
				_m.OpeningBalance = value.Float64
			}
		case balancesnapshot.FieldClosingBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field closing_balance", values[i])
			} else if value.Valid {
				_m.ClosingBalance = value.Float64
			}
		case balancesnapshot.FieldDepositTotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field deposit_total", values[i])
			} else if value.Valid {
				_m.DepositTotal = value.Float64
			}
		case balancesnapshot.FieldWithdrawTotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field withdraw_total", values[i])
			} else if value.Valid {
				_m.WithdrawTotal = value.Float64
			}
		case balancesnapshot.FieldCreditTotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_total", values[i])
			} else if value.Valid {
				_m.CreditTotal = value.Float64
			}
		case balancesnapshot.FieldUtilisationGrossTotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field utilisation_gross_total", values[i])
			} else if value.Valid {
				_m.UtilisationGrossTotal = value.Float64
			}
		case balancesnapshot.FieldUtilisationTotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field utilisation_total", values[i])
			} else if value.Valid {
				_m.UtilisationTotal = value.Float64
			}
		case balancesnapshot.FieldComputedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field computed_at", values[i])
			} else if value.Valid {
				_m.ComputedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BalanceSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *BalanceSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BalanceSnapshot.
// Note that you need to call BalanceSnapshot.Unwrap() before calling this method if this BalanceSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BalanceSnapshot) Update() *BalanceSnapshotUpdateOne {
	return NewBalanceSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BalanceSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BalanceSnapshot) Unwrap() *BalanceSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BalanceSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BalanceSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("BalanceSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("period=")
	builder.WriteString(_m.Period)
	builder.WriteString(", ")
	builder.WriteString("opening_balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.OpeningBalance))
	builder.WriteString(", ")
	builder.WriteString("closing_balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClosingBalance))
	builder.WriteString(", ")
	builder.WriteString("deposit_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.DepositTotal))
	builder.WriteString(", ")
	builder.WriteString("withdraw_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.WithdrawTotal))
	builder.WriteString(", ")
	builder.WriteString("credit_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditTotal))
	builder.WriteString(", ")
	builder.WriteString("utilisation_gross_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.UtilisationGrossTotal))
	builder.WriteString(", ")
	builder.WriteString("utilisation_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.UtilisationTotal))
	builder.WriteString(", ")
	builder.WriteString("computed_at=")
	builder.WriteString(_m.ComputedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BalanceSnapshots is a parsable slice of BalanceSnapshot.
type BalanceSnapshots []*BalanceSnapshot
