// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/enterpriseprofile"
)

// EnterpriseProfileCreate is the builder for creating a EnterpriseProfile entity.
type EnterpriseProfileCreate struct {
	config
	mutation *EnterpriseProfileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnterpriseProfileCreate) SetCreatedAt(v time.Time) *EnterpriseProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnterpriseProfileCreate) SetNillableCreatedAt(v *time.Time) *EnterpriseProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnterpriseProfileCreate) SetUpdatedAt(v time.Time) *EnterpriseProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnterpriseProfileCreate) SetNillableUpdatedAt(v *time.Time) *EnterpriseProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *EnterpriseProfileCreate) SetUserID(v int64) *EnterpriseProfileCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCompanyName sets the "company_name" field.
func (_c *EnterpriseProfileCreate) SetCompanyName(v string) *EnterpriseProfileCreate {
	_c.mutation.SetCompanyName(v)
	return _c
}

// SetContactName sets the "contact_name" field.
func (_c *EnterpriseProfileCreate) SetContactName(v string) *EnterpriseProfileCreate {
	_c.mutation.SetContactName(v)
	return _c
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_c *EnterpriseProfileCreate) SetNillableContactName(v *string) *EnterpriseProfileCreate {
	if v != nil {
		_c.SetContactName(*v)
	}
	return _c
}

// SetContactPhone sets the "contact_phone" field.
func (_c *EnterpriseProfileCreate) SetContactPhone(v string) *EnterpriseProfileCreate {
	_c.mutation.SetContactPhone(v)
	return _c
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_c *EnterpriseProfileCreate) SetNillableContactPhone(v *string) *EnterpriseProfileCreate {
	if v != nil {
		_c.SetContactPhone(*v)
	}
	return _c
}

// SetIndustry sets the "industry" field.
func (_c *EnterpriseProfileCreate) SetIndustry(v string) *EnterpriseProfileCreate {
	_c.mutation.SetIndustry(v)
	return _c
}

// SetNillableIndustry sets the "industry" field if the given value is not nil.
func (_c *EnterpriseProfileCreate) SetNillableIndustry(v *string) *EnterpriseProfileCreate {
	if v != nil {
		_c.SetIndustry(*v)
	}
	return _c
}

// Mutation returns the EnterpriseProfileMutation object of the builder.
func (_c *EnterpriseProfileCreate) Mutation() *EnterpriseProfileMutation {
	return _c.mutation
}

// Save creates the EnterpriseProfile in the database.
func (_c *EnterpriseProfileCreate) Save(ctx context.Context) (*EnterpriseProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnterpriseProfileCreate) SaveX(ctx context.Context) *EnterpriseProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnterpriseProfileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := enterpriseprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := enterpriseprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ContactName(); !ok {
		v := enterpriseprofile.DefaultContactName
		_c.mutation.SetContactName(v)
	}
	if _, ok := _c.mutation.ContactPhone(); !ok {
		v := enterpriseprofile.DefaultContactPhone
		_c.mutation.SetContactPhone(v)
	}
	if _, ok := _c.mutation.Industry(); !ok {
		v := enterpriseprofile.DefaultIndustry
		_c.mutation.SetIndustry(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnterpriseProfileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EnterpriseProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EnterpriseProfile.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "EnterpriseProfile.user_id"`)}
	}
	if _, ok := _c.mutation.CompanyName(); !ok {
		return &ValidationError{Name: "company_name", err: errors.New(`ent: missing required field "EnterpriseProfile.company_name"`)}
	}
	if v, ok := _c.mutation.CompanyName(); ok {
		if err := enterpriseprofile.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "EnterpriseProfile.company_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContactName(); !ok {
		return &ValidationError{Name: "contact_name", err: errors.New(`ent: missing required field "EnterpriseProfile.contact_name"`)}
	}
	if _, ok := _c.mutation.ContactPhone(); !ok {
		return &ValidationError{Name: "contact_phone", err: errors.New(`ent: missing required field "EnterpriseProfile.contact_phone"`)}
	}
	if v, ok := _c.mutation.ContactPhone(); ok {
		if err := enterpriseprofile.ContactPhoneValidator(v); err != nil {
			return &ValidationError{Name: "contact_phone", err: fmt.Errorf(`ent: validator failed for field "EnterpriseProfile.contact_phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Industry(); !ok {
		return &ValidationError{Name: "industry", err: errors.New(`ent: missing required field "EnterpriseProfile.industry"`)}
	}
	if v, ok := _c.mutation.Industry(); ok {
		if err := enterpriseprofile.IndustryValidator(v); err != nil {
			return &ValidationError{Name: "industry", err: fmt.Errorf(`ent: validator failed for field "EnterpriseProfile.industry": %w`, err)}
		}
	}
	return nil
}

func (_c *EnterpriseProfileCreate) sqlSave(ctx context.Context) (*EnterpriseProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnterpriseProfileCreate) createSpec() (*EnterpriseProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &EnterpriseProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enterpriseprofile.Table, sqlgraph.NewFieldSpec(enterpriseprofile.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(enterpriseprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(enterpriseprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(enterpriseprofile.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.CompanyName(); ok {
		_spec.SetField(enterpriseprofile.FieldCompanyName, field.TypeString, value)
		_node.CompanyName = value
	}
	if value, ok := _c.mutation.ContactName(); ok {
		_spec.SetField(enterpriseprofile.FieldContactName, field.TypeString, value)
		_node.ContactName = value
	}
	if value, ok := _c.mutation.ContactPhone(); ok {
		_spec.SetField(enterpriseprofile.FieldContactPhone, field.TypeString, value)
		_node.ContactPhone = value
	}
	if value, ok := _c.mutation.Industry(); ok {
		_spec.SetField(enterpriseprofile.FieldIndustry, field.TypeString, value)
		_node.Industry = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseProfile.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseProfileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseProfileCreate) OnConflict(opts ...sql.ConflictOption) *EnterpriseProfileUpsertOne {
	_c.conflict = opts
	return &EnterpriseProfileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseProfileCreate) OnConflictColumns(columns ...string) *EnterpriseProfileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseProfileUpsertOne{
		create: _c,
	}
}

type (
	// EnterpriseProfileUpsertOne is the builder for "upsert"-ing
	//  one EnterpriseProfile node.
	EnterpriseProfileUpsertOne struct {
		create *EnterpriseProfileCreate
	}

	// EnterpriseProfileUpsert is the "OnConflict" setter.
	EnterpriseProfileUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseProfileUpsert) SetUpdatedAt(v time.Time) *EnterpriseProfileUpsert {
	u.Set(enterpriseprofile.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseProfileUpsert) UpdateUpdatedAt() *EnterpriseProfileUpsert {
	u.SetExcluded(enterpriseprofile.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *EnterpriseProfileUpsert) SetUserID(v int64) *EnterpriseProfileUpsert {
	u.Set(enterpriseprofile.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EnterpriseProfileUpsert) UpdateUserID() *EnterpriseProfileUpsert {
	u.SetExcluded(enterpriseprofile.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *EnterpriseProfileUpsert) AddUserID(v int64) *EnterpriseProfileUpsert {
	u.Add(enterpriseprofile.FieldUserID, v)
	return u
}

// SetCompanyName sets the "company_name" field.
func (u *EnterpriseProfileUpsert) SetCompanyName(v string) *EnterpriseProfileUpsert {
	u.Set(enterpriseprofile.FieldCompanyName, v)
	return u
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *EnterpriseProfileUpsert) UpdateCompanyName() *EnterpriseProfileUpsert {
	u.SetExcluded(enterpriseprofile.FieldCompanyName)
	return u
}

// SetContactName sets the "contact_name" field.
func (u *EnterpriseProfileUpsert) SetContactName(v string) *EnterpriseProfileUpsert {
	u.Set(enterpriseprofile.FieldContactName, v)
	return u
}

// UpdateContactName sets the "contact_name" field to the value that was provided on create.
func (u *EnterpriseProfileUpsert) UpdateContactName() *EnterpriseProfileUpsert {
	u.SetExcluded(enterpriseprofile.FieldContactName)
	return u
}

// SetContactPhone sets the "contact_phone" field.
func (u *EnterpriseProfileUpsert) SetContactPhone(v string) *EnterpriseProfileUpsert {
	u.Set(enterpriseprofile.FieldContactPhone, v)
	return u
}

// UpdateContactPhone sets the "contact_phone" field to the value that was provided on create.
func (u *EnterpriseProfileUpsert) UpdateContactPhone() *EnterpriseProfileUpsert {
	u.SetExcluded(enterpriseprofile.FieldContactPhone)
	return u
}

// SetIndustry sets the "industry" field.
func (u *EnterpriseProfileUpsert) SetIndustry(v string) *EnterpriseProfileUpsert {
	u.Set(enterpriseprofile.FieldIndustry, v)
	return u
}

// UpdateIndustry sets the "industry" field to the value that was provided on create.
func (u *EnterpriseProfileUpsert) UpdateIndustry() *EnterpriseProfileUpsert {
	u.SetExcluded(enterpriseprofile.FieldIndustry)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EnterpriseProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseProfileUpsertOne) UpdateNewValues() *EnterpriseProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(enterpriseprofile.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseProfile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnterpriseProfileUpsertOne) Ignore() *EnterpriseProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseProfileUpsertOne) DoNothing() *EnterpriseProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseProfileCreate.OnConflict
// documentation for more info.
func (u *EnterpriseProfileUpsertOne) Update(set func(*EnterpriseProfileUpsert)) *EnterpriseProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseProfileUpsertOne) SetUpdatedAt(v time.Time) *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseProfileUpsertOne) UpdateUpdatedAt() *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *EnterpriseProfileUpsertOne) SetUserID(v int64) *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *EnterpriseProfileUpsertOne) AddUserID(v int64) *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EnterpriseProfileUpsertOne) UpdateUserID() *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.UpdateUserID()
	})
}

// SetCompanyName sets the "company_name" field.
func (u *EnterpriseProfileUpsertOne) SetCompanyName(v string) *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *EnterpriseProfileUpsertOne) UpdateCompanyName() *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.UpdateCompanyName()
	})
}

// SetContactName sets the "contact_name" field.
func (u *EnterpriseProfileUpsertOne) SetContactName(v string) *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.SetContactName(v)
	})
}

// UpdateContactName sets the "contact_name" field to the value that was provided on create.
func (u *EnterpriseProfileUpsertOne) UpdateContactName() *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.UpdateContactName()
	})
}

// SetContactPhone sets the "contact_phone" field.
func (u *EnterpriseProfileUpsertOne) SetContactPhone(v string) *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.SetContactPhone(v)
	})
}

// UpdateContactPhone sets the "contact_phone" field to the value that was provided on create.
func (u *EnterpriseProfileUpsertOne) UpdateContactPhone() *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.UpdateContactPhone()
	})
}

// SetIndustry sets the "industry" field.
func (u *EnterpriseProfileUpsertOne) SetIndustry(v string) *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.SetIndustry(v)
	})
}

// UpdateIndustry sets the "industry" field to the value that was provided on create.
func (u *EnterpriseProfileUpsertOne) UpdateIndustry() *EnterpriseProfileUpsertOne {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.UpdateIndustry()
	})
}

// Exec executes the query.
func (u *EnterpriseProfileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseProfileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseProfileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EnterpriseProfileUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EnterpriseProfileUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EnterpriseProfileCreateBulk is the builder for creating many EnterpriseProfile entities in bulk.
type EnterpriseProfileCreateBulk struct {
	config
	err      error
	builders []*EnterpriseProfileCreate
	conflict []sql.ConflictOption
}

// Save creates the EnterpriseProfile entities in the database.
func (_c *EnterpriseProfileCreateBulk) Save(ctx context.Context) ([]*EnterpriseProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnterpriseProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnterpriseProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnterpriseProfileCreateBulk) SaveX(ctx context.Context) []*EnterpriseProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseProfile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseProfileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseProfileCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnterpriseProfileUpsertBulk {
	_c.conflict = opts
	return &EnterpriseProfileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseProfileCreateBulk) OnConflictColumns(columns ...string) *EnterpriseProfileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseProfileUpsertBulk{
		create: _c,
	}
}

// EnterpriseProfileUpsertBulk is the builder for "upsert"-ing
// a bulk of EnterpriseProfile nodes.
type EnterpriseProfileUpsertBulk struct {
	create *EnterpriseProfileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EnterpriseProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseProfileUpsertBulk) UpdateNewValues() *EnterpriseProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(enterpriseprofile.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseProfile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnterpriseProfileUpsertBulk) Ignore() *EnterpriseProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseProfileUpsertBulk) DoNothing() *EnterpriseProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseProfileCreateBulk.OnConflict
// documentation for more info.
func (u *EnterpriseProfileUpsertBulk) Update(set func(*EnterpriseProfileUpsert)) *EnterpriseProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseProfileUpsertBulk) SetUpdatedAt(v time.Time) *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseProfileUpsertBulk) UpdateUpdatedAt() *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *EnterpriseProfileUpsertBulk) SetUserID(v int64) *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *EnterpriseProfileUpsertBulk) AddUserID(v int64) *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EnterpriseProfileUpsertBulk) UpdateUserID() *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.UpdateUserID()
	})
}

// SetCompanyName sets the "company_name" field.
func (u *EnterpriseProfileUpsertBulk) SetCompanyName(v string) *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *EnterpriseProfileUpsertBulk) UpdateCompanyName() *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.UpdateCompanyName()
	})
}

// SetContactName sets the "contact_name" field.
func (u *EnterpriseProfileUpsertBulk) SetContactName(v string) *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.SetContactName(v)
	})
}

// UpdateContactName sets the "contact_name" field to the value that was provided on create.
func (u *EnterpriseProfileUpsertBulk) UpdateContactName() *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.UpdateContactName()
	})
}

// SetContactPhone sets the "contact_phone" field.
func (u *EnterpriseProfileUpsertBulk) SetContactPhone(v string) *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.SetContactPhone(v)
	})
}

// UpdateContactPhone sets the "contact_phone" field to the value that was provided on create.
func (u *EnterpriseProfileUpsertBulk) UpdateContactPhone() *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.UpdateContactPhone()
	})
}

// SetIndustry sets the "industry" field.
func (u *EnterpriseProfileUpsertBulk) SetIndustry(v string) *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.SetIndustry(v)
	})
}

// UpdateIndustry sets the "industry" field to the value that was provided on create.
func (u *EnterpriseProfileUpsertBulk) UpdateIndustry() *EnterpriseProfileUpsertBulk {
	return u.Update(func(s *EnterpriseProfileUpsert) {
		s.UpdateIndustry()
	})
}

// Exec executes the query.
func (u *EnterpriseProfileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnterpriseProfileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseProfileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseProfileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
