// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelpricing"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelPricingUpdate is the builder for updating ModelPricing entities.
type ModelPricingUpdate struct {
	config
	hooks    []Hook
	mutation *ModelPricingMutation
}

// Where appends a list predicates to the ModelPricingUpdate builder.
func (_u *ModelPricingUpdate) Where(ps ...predicate.ModelPricing) *ModelPricingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelPricingUpdate) SetModelID(v string) *ModelPricingUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableModelID(v *string) *ModelPricingUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ModelPricingUpdate) SetDisplayName(v string) *ModelPricingUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableDisplayName(v *string) *ModelPricingUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *ModelPricingUpdate) ClearDisplayName() *ModelPricingUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModelPricingUpdate) SetDescription(v string) *ModelPricingUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableDescription(v *string) *ModelPricingUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ModelPricingUpdate) ClearDescription() *ModelPricingUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ModelPricingUpdate) SetProvider(v string) *ModelPricingUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableProvider(v *string) *ModelPricingUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *ModelPricingUpdate) SetMode(v string) *ModelPricingUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableMode(v *string) *ModelPricingUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetInputCostPerToken sets the "input_cost_per_token" field.
func (_u *ModelPricingUpdate) SetInputCostPerToken(v float64) *ModelPricingUpdate {
	_u.mutation.ResetInputCostPerToken()
	_u.mutation.SetInputCostPerToken(v)
	return _u
}

// SetNillableInputCostPerToken sets the "input_cost_per_token" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableInputCostPerToken(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetInputCostPerToken(*v)
	}
	return _u
}

// AddInputCostPerToken adds value to the "input_cost_per_token" field.
func (_u *ModelPricingUpdate) AddInputCostPerToken(v float64) *ModelPricingUpdate {
	_u.mutation.AddInputCostPerToken(v)
	return _u
}

// ClearInputCostPerToken clears the value of the "input_cost_per_token" field.
func (_u *ModelPricingUpdate) ClearInputCostPerToken() *ModelPricingUpdate {
	_u.mutation.ClearInputCostPerToken()
	return _u
}

// SetOutputCostPerToken sets the "output_cost_per_token" field.
func (_u *ModelPricingUpdate) SetOutputCostPerToken(v float64) *ModelPricingUpdate {
	_u.mutation.ResetOutputCostPerToken()
	_u.mutation.SetOutputCostPerToken(v)
	return _u
}

// SetNillableOutputCostPerToken sets the "output_cost_per_token" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableOutputCostPerToken(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetOutputCostPerToken(*v)
	}
	return _u
}

// AddOutputCostPerToken adds value to the "output_cost_per_token" field.
func (_u *ModelPricingUpdate) AddOutputCostPerToken(v float64) *ModelPricingUpdate {
	_u.mutation.AddOutputCostPerToken(v)
	return _u
}

// ClearOutputCostPerToken clears the value of the "output_cost_per_token" field.
func (_u *ModelPricingUpdate) ClearOutputCostPerToken() *ModelPricingUpdate {
	_u.mutation.ClearOutputCostPerToken()
	return _u
}

// SetCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field.
func (_u *ModelPricingUpdate) SetCacheCreationInputTokenCost(v float64) *ModelPricingUpdate {
	_u.mutation.ResetCacheCreationInputTokenCost()
	_u.mutation.SetCacheCreationInputTokenCost(v)
	return _u
}

// SetNillableCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableCacheCreationInputTokenCost(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetCacheCreationInputTokenCost(*v)
	}
	return _u
}

// AddCacheCreationInputTokenCost adds value to the "cache_creation_input_token_cost" field.
func (_u *ModelPricingUpdate) AddCacheCreationInputTokenCost(v float64) *ModelPricingUpdate {
	_u.mutation.AddCacheCreationInputTokenCost(v)
	return _u
}

// ClearCacheCreationInputTokenCost clears the value of the "cache_creation_input_token_cost" field.
func (_u *ModelPricingUpdate) ClearCacheCreationInputTokenCost() *ModelPricingUpdate {
	_u.mutation.ClearCacheCreationInputTokenCost()
	return _u
}

// SetCacheReadInputTokenCost sets the "cache_read_input_token_cost" field.
func (_u *ModelPricingUpdate) SetCacheReadInputTokenCost(v float64) *ModelPricingUpdate {
	_u.mutation.ResetCacheReadInputTokenCost()
	_u.mutation.SetCacheReadInputTokenCost(v)
	return _u
}

// SetNillableCacheReadInputTokenCost sets the "cache_read_input_token_cost" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableCacheReadInputTokenCost(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetCacheReadInputTokenCost(*v)
	}
	return _u
}

// AddCacheReadInputTokenCost adds value to the "cache_read_input_token_cost" field.
func (_u *ModelPricingUpdate) AddCacheReadInputTokenCost(v float64) *ModelPricingUpdate {
	_u.mutation.AddCacheReadInputTokenCost(v)
	return _u
}

// ClearCacheReadInputTokenCost clears the value of the "cache_read_input_token_cost" field.
func (_u *ModelPricingUpdate) ClearCacheReadInputTokenCost() *ModelPricingUpdate {
	_u.mutation.ClearCacheReadInputTokenCost()
	return _u
}

// SetOutputCostPerImage sets the "output_cost_per_image" field.
func (_u *ModelPricingUpdate) SetOutputCostPerImage(v float64) *ModelPricingUpdate {
	_u.mutation.ResetOutputCostPerImage()
	_u.mutation.SetOutputCostPerImage(v)
	return _u
}

// SetNillableOutputCostPerImage sets the "output_cost_per_image" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableOutputCostPerImage(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetOutputCostPerImage(*v)
	}
	return _u
}

// AddOutputCostPerImage adds value to the "output_cost_per_image" field.
func (_u *ModelPricingUpdate) AddOutputCostPerImage(v float64) *ModelPricingUpdate {
	_u.mutation.AddOutputCostPerImage(v)
	return _u
}

// ClearOutputCostPerImage clears the value of the "output_cost_per_image" field.
func (_u *ModelPricingUpdate) ClearOutputCostPerImage() *ModelPricingUpdate {
	_u.mutation.ClearOutputCostPerImage()
	return _u
}

// SetOutputCostPerImageToken sets the "output_cost_per_image_token" field.
func (_u *ModelPricingUpdate) SetOutputCostPerImageToken(v float64) *ModelPricingUpdate {
	_u.mutation.ResetOutputCostPerImageToken()
	_u.mutation.SetOutputCostPerImageToken(v)
	return _u
}

// SetNillableOutputCostPerImageToken sets the "output_cost_per_image_token" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableOutputCostPerImageToken(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetOutputCostPerImageToken(*v)
	}
	return _u
}

// AddOutputCostPerImageToken adds value to the "output_cost_per_image_token" field.
func (_u *ModelPricingUpdate) AddOutputCostPerImageToken(v float64) *ModelPricingUpdate {
	_u.mutation.AddOutputCostPerImageToken(v)
	return _u
}

// ClearOutputCostPerImageToken clears the value of the "output_cost_per_image_token" field.
func (_u *ModelPricingUpdate) ClearOutputCostPerImageToken() *ModelPricingUpdate {
	_u.mutation.ClearOutputCostPerImageToken()
	return _u
}

// SetSupportsPromptCaching sets the "supports_prompt_caching" field.
func (_u *ModelPricingUpdate) SetSupportsPromptCaching(v bool) *ModelPricingUpdate {
	_u.mutation.SetSupportsPromptCaching(v)
	return _u
}

// SetNillableSupportsPromptCaching sets the "supports_prompt_caching" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableSupportsPromptCaching(v *bool) *ModelPricingUpdate {
	if v != nil {
		_u.SetSupportsPromptCaching(*v)
	}
	return _u
}

// SetCustomInputCost sets the "custom_input_cost" field.
func (_u *ModelPricingUpdate) SetCustomInputCost(v float64) *ModelPricingUpdate {
	_u.mutation.ResetCustomInputCost()
	_u.mutation.SetCustomInputCost(v)
	return _u
}

// SetNillableCustomInputCost sets the "custom_input_cost" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableCustomInputCost(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetCustomInputCost(*v)
	}
	return _u
}

// AddCustomInputCost adds value to the "custom_input_cost" field.
func (_u *ModelPricingUpdate) AddCustomInputCost(v float64) *ModelPricingUpdate {
	_u.mutation.AddCustomInputCost(v)
	return _u
}

// ClearCustomInputCost clears the value of the "custom_input_cost" field.
func (_u *ModelPricingUpdate) ClearCustomInputCost() *ModelPricingUpdate {
	_u.mutation.ClearCustomInputCost()
	return _u
}

// SetCustomOutputCost sets the "custom_output_cost" field.
func (_u *ModelPricingUpdate) SetCustomOutputCost(v float64) *ModelPricingUpdate {
	_u.mutation.ResetCustomOutputCost()
	_u.mutation.SetCustomOutputCost(v)
	return _u
}

// SetNillableCustomOutputCost sets the "custom_output_cost" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableCustomOutputCost(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetCustomOutputCost(*v)
	}
	return _u
}

// AddCustomOutputCost adds value to the "custom_output_cost" field.
func (_u *ModelPricingUpdate) AddCustomOutputCost(v float64) *ModelPricingUpdate {
	_u.mutation.AddCustomOutputCost(v)
	return _u
}

// ClearCustomOutputCost clears the value of the "custom_output_cost" field.
func (_u *ModelPricingUpdate) ClearCustomOutputCost() *ModelPricingUpdate {
	_u.mutation.ClearCustomOutputCost()
	return _u
}

// SetDiscountRate sets the "discount_rate" field.
func (_u *ModelPricingUpdate) SetDiscountRate(v float64) *ModelPricingUpdate {
	_u.mutation.ResetDiscountRate()
	_u.mutation.SetDiscountRate(v)
	return _u
}

// SetNillableDiscountRate sets the "discount_rate" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableDiscountRate(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetDiscountRate(*v)
	}
	return _u
}

// AddDiscountRate adds value to the "discount_rate" field.
func (_u *ModelPricingUpdate) AddDiscountRate(v float64) *ModelPricingUpdate {
	_u.mutation.AddDiscountRate(v)
	return _u
}

// ClearDiscountRate clears the value of the "discount_rate" field.
func (_u *ModelPricingUpdate) ClearDiscountRate() *ModelPricingUpdate {
	_u.mutation.ClearDiscountRate()
	return _u
}

// SetIsCustom sets the "is_custom" field.
func (_u *ModelPricingUpdate) SetIsCustom(v bool) *ModelPricingUpdate {
	_u.mutation.SetIsCustom(v)
	return _u
}

// SetNillableIsCustom sets the "is_custom" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableIsCustom(v *bool) *ModelPricingUpdate {
	if v != nil {
		_u.SetIsCustom(*v)
	}
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *ModelPricingUpdate) SetIsEnabled(v bool) *ModelPricingUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableIsEnabled(v *bool) *ModelPricingUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *ModelPricingUpdate) SetLastSyncedAt(v time.Time) *ModelPricingUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableLastSyncedAt(v *time.Time) *ModelPricingUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *ModelPricingUpdate) ClearLastSyncedAt() *ModelPricingUpdate {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelPricingUpdate) SetUpdatedAt(v time.Time) *ModelPricingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ModelPricingMutation object of the builder.
func (_u *ModelPricingUpdate) Mutation() *ModelPricingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelPricingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPricingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelPricingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPricingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelPricingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelpricing.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelPricingUpdate) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := modelpricing.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := modelpricing.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := modelpricing.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := modelpricing.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.mode": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelPricingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelpricing.Table, modelpricing.Columns, sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelpricing.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(modelpricing.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(modelpricing.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(modelpricing.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(modelpricing.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(modelpricing.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(modelpricing.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputCostPerToken(); ok {
		_spec.SetField(modelpricing.FieldInputCostPerToken, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputCostPerToken(); ok {
		_spec.AddField(modelpricing.FieldInputCostPerToken, field.TypeFloat64, value)
	}
	if _u.mutation.InputCostPerTokenCleared() {
		_spec.ClearField(modelpricing.FieldInputCostPerToken, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputCostPerToken(); ok {
		_spec.SetField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputCostPerToken(); ok {
		_spec.AddField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64, value)
	}
	if _u.mutation.OutputCostPerTokenCleared() {
		_spec.ClearField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheCreationInputTokenCost(); ok {
		_spec.SetField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationInputTokenCost(); ok {
		_spec.AddField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64, value)
	}
	if _u.mutation.CacheCreationInputTokenCostCleared() {
		_spec.ClearField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadInputTokenCost(); ok {
		_spec.SetField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadInputTokenCost(); ok {
		_spec.AddField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadInputTokenCostCleared() {
		_spec.ClearField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputCostPerImage(); ok {
		_spec.SetField(modelpricing.FieldOutputCostPerImage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputCostPerImage(); ok {
		_spec.AddField(modelpricing.FieldOutputCostPerImage, field.TypeFloat64, value)
	}
	if _u.mutation.OutputCostPerImageCleared() {
		_spec.ClearField(modelpricing.FieldOutputCostPerImage, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputCostPerImageToken(); ok {
		_spec.SetField(modelpricing.FieldOutputCostPerImageToken, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputCostPerImageToken(); ok {
		_spec.AddField(modelpricing.FieldOutputCostPerImageToken, field.TypeFloat64, value)
	}
	if _u.mutation.OutputCostPerImageTokenCleared() {
		_spec.ClearField(modelpricing.FieldOutputCostPerImageToken, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SupportsPromptCaching(); ok {
		_spec.SetField(modelpricing.FieldSupportsPromptCaching, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CustomInputCost(); ok {
		_spec.SetField(modelpricing.FieldCustomInputCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCustomInputCost(); ok {
		_spec.AddField(modelpricing.FieldCustomInputCost, field.TypeFloat64, value)
	}
	if _u.mutation.CustomInputCostCleared() {
		_spec.ClearField(modelpricing.FieldCustomInputCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CustomOutputCost(); ok {
		_spec.SetField(modelpricing.FieldCustomOutputCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCustomOutputCost(); ok {
		_spec.AddField(modelpricing.FieldCustomOutputCost, field.TypeFloat64, value)
	}
	if _u.mutation.CustomOutputCostCleared() {
		_spec.ClearField(modelpricing.FieldCustomOutputCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DiscountRate(); ok {
		_spec.SetField(modelpricing.FieldDiscountRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountRate(); ok {
		_spec.AddField(modelpricing.FieldDiscountRate, field.TypeFloat64, value)
	}
	if _u.mutation.DiscountRateCleared() {
		_spec.ClearField(modelpricing.FieldDiscountRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IsCustom(); ok {
		_spec.SetField(modelpricing.FieldIsCustom, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(modelpricing.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(modelpricing.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(modelpricing.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpricing.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpricing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelPricingUpdateOne is the builder for updating a single ModelPricing entity.
type ModelPricingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelPricingMutation
}

// SetModelID sets the "model_id" field.
func (_u *ModelPricingUpdateOne) SetModelID(v string) *ModelPricingUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableModelID(v *string) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ModelPricingUpdateOne) SetDisplayName(v string) *ModelPricingUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableDisplayName(v *string) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *ModelPricingUpdateOne) ClearDisplayName() *ModelPricingUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModelPricingUpdateOne) SetDescription(v string) *ModelPricingUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableDescription(v *string) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ModelPricingUpdateOne) ClearDescription() *ModelPricingUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ModelPricingUpdateOne) SetProvider(v string) *ModelPricingUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableProvider(v *string) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *ModelPricingUpdateOne) SetMode(v string) *ModelPricingUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableMode(v *string) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetInputCostPerToken sets the "input_cost_per_token" field.
func (_u *ModelPricingUpdateOne) SetInputCostPerToken(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetInputCostPerToken()
	_u.mutation.SetInputCostPerToken(v)
	return _u
}

// SetNillableInputCostPerToken sets the "input_cost_per_token" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableInputCostPerToken(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetInputCostPerToken(*v)
	}
	return _u
}

// AddInputCostPerToken adds value to the "input_cost_per_token" field.
func (_u *ModelPricingUpdateOne) AddInputCostPerToken(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddInputCostPerToken(v)
	return _u
}

// ClearInputCostPerToken clears the value of the "input_cost_per_token" field.
func (_u *ModelPricingUpdateOne) ClearInputCostPerToken() *ModelPricingUpdateOne {
	_u.mutation.ClearInputCostPerToken()
	return _u
}

// SetOutputCostPerToken sets the "output_cost_per_token" field.
func (_u *ModelPricingUpdateOne) SetOutputCostPerToken(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetOutputCostPerToken()
	_u.mutation.SetOutputCostPerToken(v)
	return _u
}

// SetNillableOutputCostPerToken sets the "output_cost_per_token" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableOutputCostPerToken(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetOutputCostPerToken(*v)
	}
	return _u
}

// AddOutputCostPerToken adds value to the "output_cost_per_token" field.
func (_u *ModelPricingUpdateOne) AddOutputCostPerToken(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddOutputCostPerToken(v)
	return _u
}

// ClearOutputCostPerToken clears the value of the "output_cost_per_token" field.
func (_u *ModelPricingUpdateOne) ClearOutputCostPerToken() *ModelPricingUpdateOne {
	_u.mutation.ClearOutputCostPerToken()
	return _u
}

// SetCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field.
func (_u *ModelPricingUpdateOne) SetCacheCreationInputTokenCost(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetCacheCreationInputTokenCost()
	_u.mutation.SetCacheCreationInputTokenCost(v)
	return _u
}

// SetNillableCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableCacheCreationInputTokenCost(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetCacheCreationInputTokenCost(*v)
	}
	return _u
}

// AddCacheCreationInputTokenCost adds value to the "cache_creation_input_token_cost" field.
func (_u *ModelPricingUpdateOne) AddCacheCreationInputTokenCost(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddCacheCreationInputTokenCost(v)
	return _u
}

// ClearCacheCreationInputTokenCost clears the value of the "cache_creation_input_token_cost" field.
func (_u *ModelPricingUpdateOne) ClearCacheCreationInputTokenCost() *ModelPricingUpdateOne {
	_u.mutation.ClearCacheCreationInputTokenCost()
	return _u
}

// SetCacheReadInputTokenCost sets the "cache_read_input_token_cost" field.
func (_u *ModelPricingUpdateOne) SetCacheReadInputTokenCost(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetCacheReadInputTokenCost()
	_u.mutation.SetCacheReadInputTokenCost(v)
	return _u
}

// SetNillableCacheReadInputTokenCost sets the "cache_read_input_token_cost" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableCacheReadInputTokenCost(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetCacheReadInputTokenCost(*v)
	}
	return _u
}

// AddCacheReadInputTokenCost adds value to the "cache_read_input_token_cost" field.
func (_u *ModelPricingUpdateOne) AddCacheReadInputTokenCost(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddCacheReadInputTokenCost(v)
	return _u
}

// ClearCacheReadInputTokenCost clears the value of the "cache_read_input_token_cost" field.
func (_u *ModelPricingUpdateOne) ClearCacheReadInputTokenCost() *ModelPricingUpdateOne {
	_u.mutation.ClearCacheReadInputTokenCost()
	return _u
}

// SetOutputCostPerImage sets the "output_cost_per_image" field.
func (_u *ModelPricingUpdateOne) SetOutputCostPerImage(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetOutputCostPerImage()
	_u.mutation.SetOutputCostPerImage(v)
	return _u
}

// SetNillableOutputCostPerImage sets the "output_cost_per_image" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableOutputCostPerImage(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetOutputCostPerImage(*v)
	}
	return _u
}

// AddOutputCostPerImage adds value to the "output_cost_per_image" field.
func (_u *ModelPricingUpdateOne) AddOutputCostPerImage(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddOutputCostPerImage(v)
	return _u
}

// ClearOutputCostPerImage clears the value of the "output_cost_per_image" field.
func (_u *ModelPricingUpdateOne) ClearOutputCostPerImage() *ModelPricingUpdateOne {
	_u.mutation.ClearOutputCostPerImage()
	return _u
}

// SetOutputCostPerImageToken sets the "output_cost_per_image_token" field.
func (_u *ModelPricingUpdateOne) SetOutputCostPerImageToken(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetOutputCostPerImageToken()
	_u.mutation.SetOutputCostPerImageToken(v)
	return _u
}

// SetNillableOutputCostPerImageToken sets the "output_cost_per_image_token" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableOutputCostPerImageToken(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetOutputCostPerImageToken(*v)
	}
	return _u
}

// AddOutputCostPerImageToken adds value to the "output_cost_per_image_token" field.
func (_u *ModelPricingUpdateOne) AddOutputCostPerImageToken(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddOutputCostPerImageToken(v)
	return _u
}

// ClearOutputCostPerImageToken clears the value of the "output_cost_per_image_token" field.
func (_u *ModelPricingUpdateOne) ClearOutputCostPerImageToken() *ModelPricingUpdateOne {
	_u.mutation.ClearOutputCostPerImageToken()
	return _u
}

// SetSupportsPromptCaching sets the "supports_prompt_caching" field.
func (_u *ModelPricingUpdateOne) SetSupportsPromptCaching(v bool) *ModelPricingUpdateOne {
	_u.mutation.SetSupportsPromptCaching(v)
	return _u
}

// SetNillableSupportsPromptCaching sets the "supports_prompt_caching" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableSupportsPromptCaching(v *bool) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetSupportsPromptCaching(*v)
	}
	return _u
}

// SetCustomInputCost sets the "custom_input_cost" field.
func (_u *ModelPricingUpdateOne) SetCustomInputCost(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetCustomInputCost()
	_u.mutation.SetCustomInputCost(v)
	return _u
}

// SetNillableCustomInputCost sets the "custom_input_cost" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableCustomInputCost(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetCustomInputCost(*v)
	}
	return _u
}

// AddCustomInputCost adds value to the "custom_input_cost" field.
func (_u *ModelPricingUpdateOne) AddCustomInputCost(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddCustomInputCost(v)
	return _u
}

// ClearCustomInputCost clears the value of the "custom_input_cost" field.
func (_u *ModelPricingUpdateOne) ClearCustomInputCost() *ModelPricingUpdateOne {
	_u.mutation.ClearCustomInputCost()
	return _u
}

// SetCustomOutputCost sets the "custom_output_cost" field.
func (_u *ModelPricingUpdateOne) SetCustomOutputCost(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetCustomOutputCost()
	_u.mutation.SetCustomOutputCost(v)
	return _u
}

// SetNillableCustomOutputCost sets the "custom_output_cost" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableCustomOutputCost(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetCustomOutputCost(*v)
	}
	return _u
}

// AddCustomOutputCost adds value to the "custom_output_cost" field.
func (_u *ModelPricingUpdateOne) AddCustomOutputCost(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddCustomOutputCost(v)
	return _u
}

// ClearCustomOutputCost clears the value of the "custom_output_cost" field.
func (_u *ModelPricingUpdateOne) ClearCustomOutputCost() *ModelPricingUpdateOne {
	_u.mutation.ClearCustomOutputCost()
	return _u
}

// SetDiscountRate sets the "discount_rate" field.
func (_u *ModelPricingUpdateOne) SetDiscountRate(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetDiscountRate()
	_u.mutation.SetDiscountRate(v)
	return _u
}

// SetNillableDiscountRate sets the "discount_rate" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableDiscountRate(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetDiscountRate(*v)
	}
	return _u
}

// AddDiscountRate adds value to the "discount_rate" field.
func (_u *ModelPricingUpdateOne) AddDiscountRate(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddDiscountRate(v)
	return _u
}

// ClearDiscountRate clears the value of the "discount_rate" field.
func (_u *ModelPricingUpdateOne) ClearDiscountRate() *ModelPricingUpdateOne {
	_u.mutation.ClearDiscountRate()
	return _u
}

// SetIsCustom sets the "is_custom" field.
func (_u *ModelPricingUpdateOne) SetIsCustom(v bool) *ModelPricingUpdateOne {
	_u.mutation.SetIsCustom(v)
	return _u
}

// SetNillableIsCustom sets the "is_custom" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableIsCustom(v *bool) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetIsCustom(*v)
	}
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *ModelPricingUpdateOne) SetIsEnabled(v bool) *ModelPricingUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableIsEnabled(v *bool) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *ModelPricingUpdateOne) SetLastSyncedAt(v time.Time) *ModelPricingUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableLastSyncedAt(v *time.Time) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *ModelPricingUpdateOne) ClearLastSyncedAt() *ModelPricingUpdateOne {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelPricingUpdateOne) SetUpdatedAt(v time.Time) *ModelPricingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ModelPricingMutation object of the builder.
func (_u *ModelPricingUpdateOne) Mutation() *ModelPricingMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelPricingUpdate builder.
func (_u *ModelPricingUpdateOne) Where(ps ...predicate.ModelPricing) *ModelPricingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelPricingUpdateOne) Select(field string, fields ...string) *ModelPricingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelPricing entity.
func (_u *ModelPricingUpdateOne) Save(ctx context.Context) (*ModelPricing, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPricingUpdateOne) SaveX(ctx context.Context) *ModelPricing {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelPricingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPricingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelPricingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelpricing.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelPricingUpdateOne) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := modelpricing.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := modelpricing.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := modelpricing.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := modelpricing.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.mode": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelPricingUpdateOne) sqlSave(ctx context.Context) (_node *ModelPricing, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelpricing.Table, modelpricing.Columns, sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelPricing.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelpricing.FieldID)
		for _, f := range fields {
			if !modelpricing.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelpricing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelpricing.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(modelpricing.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(modelpricing.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(modelpricing.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(modelpricing.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(modelpricing.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(modelpricing.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputCostPerToken(); ok {
		_spec.SetField(modelpricing.FieldInputCostPerToken, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputCostPerToken(); ok {
		_spec.AddField(modelpricing.FieldInputCostPerToken, field.TypeFloat64, value)
	}
	if _u.mutation.InputCostPerTokenCleared() {
		_spec.ClearField(modelpricing.FieldInputCostPerToken, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputCostPerToken(); ok {
		_spec.SetField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputCostPerToken(); ok {
		_spec.AddField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64, value)
	}
	if _u.mutation.OutputCostPerTokenCleared() {
		_spec.ClearField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheCreationInputTokenCost(); ok {
		_spec.SetField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationInputTokenCost(); ok {
		_spec.AddField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64, value)
	}
	if _u.mutation.CacheCreationInputTokenCostCleared() {
		_spec.ClearField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadInputTokenCost(); ok {
		_spec.SetField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadInputTokenCost(); ok {
		_spec.AddField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadInputTokenCostCleared() {
		_spec.ClearField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputCostPerImage(); ok {
		_spec.SetField(modelpricing.FieldOutputCostPerImage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputCostPerImage(); ok {
		_spec.AddField(modelpricing.FieldOutputCostPerImage, field.TypeFloat64, value)
	}
	if _u.mutation.OutputCostPerImageCleared() {
		_spec.ClearField(modelpricing.FieldOutputCostPerImage, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputCostPerImageToken(); ok {
		_spec.SetField(modelpricing.FieldOutputCostPerImageToken, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputCostPerImageToken(); ok {
		_spec.AddField(modelpricing.FieldOutputCostPerImageToken, field.TypeFloat64, value)
	}
	if _u.mutation.OutputCostPerImageTokenCleared() {
		_spec.ClearField(modelpricing.FieldOutputCostPerImageToken, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SupportsPromptCaching(); ok {
		_spec.SetField(modelpricing.FieldSupportsPromptCaching, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CustomInputCost(); ok {
		_spec.SetField(modelpricing.FieldCustomInputCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCustomInputCost(); ok {
		_spec.AddField(modelpricing.FieldCustomInputCost, field.TypeFloat64, value)
	}
	if _u.mutation.CustomInputCostCleared() {
		_spec.ClearField(modelpricing.FieldCustomInputCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CustomOutputCost(); ok {
		_spec.SetField(modelpricing.FieldCustomOutputCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCustomOutputCost(); ok {
		_spec.AddField(modelpricing.FieldCustomOutputCost, field.TypeFloat64, value)
	}
	if _u.mutation.CustomOutputCostCleared() {
		_spec.ClearField(modelpricing.FieldCustomOutputCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DiscountRate(); ok {
		_spec.SetField(modelpricing.FieldDiscountRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountRate(); ok {
		_spec.AddField(modelpricing.FieldDiscountRate, field.TypeFloat64, value)
	}
	if _u.mutation.DiscountRateCleared() {
		_spec.ClearField(modelpricing.FieldDiscountRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IsCustom(); ok {
		_spec.SetField(modelpricing.FieldIsCustom, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(modelpricing.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(modelpricing.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(modelpricing.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpricing.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ModelPricing{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpricing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
