// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/providerpricing"
)

// ProviderPricing is the model entity for the ProviderPricing schema.
type ProviderPricing struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// BillingMode holds the value of the "billing_mode" field.
	BillingMode string `json:"billing_mode,omitempty"`
	// InputPrice holds the value of the "input_price" field.
	InputPrice float64 `json:"input_price,omitempty"`
	// OutputPrice holds the value of the "output_price" field.
	OutputPrice float64 `json:"output_price,omitempty"`
	// CacheCreationPrice holds the value of the "cache_creation_price" field.
	CacheCreationPrice float64 `json:"cache_creation_price,omitempty"`
	// CacheReadPrice holds the value of the "cache_read_price" field.
	CacheReadPrice float64 `json:"cache_read_price,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// EffectiveFrom holds the value of the "effective_from" field.
	EffectiveFrom time.Time `json:"effective_from,omitempty"`
	// EffectiveTo holds the value of the "effective_to" field.
	EffectiveTo *time.Time `json:"effective_to,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderPricing) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providerpricing.FieldInputPrice, providerpricing.FieldOutputPrice, providerpricing.FieldCacheCreationPrice, providerpricing.FieldCacheReadPrice:
			values[i] = new(sql.NullFloat64)
		case providerpricing.FieldID:
			values[i] = new(sql.NullInt64)
		case providerpricing.FieldProvider, providerpricing.FieldModel, providerpricing.FieldBillingMode, providerpricing.FieldCurrency, providerpricing.FieldSource:
			values[i] = new(sql.NullString)
		case providerpricing.FieldEffectiveFrom, providerpricing.FieldEffectiveTo, providerpricing.FieldCreatedAt, providerpricing.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderPricing fields.
func (_m *ProviderPricing) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providerpricing.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case providerpricing.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case providerpricing.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case providerpricing.FieldBillingMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_mode", values[i])
			} else if value.Valid {
				_m.BillingMode = value.String
			}
		case providerpricing.FieldInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_price", values[i])
			} else if value.Valid {
				_m.InputPrice = value.Float64
			}
		case providerpricing.FieldOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_price", values[i])
			} else if value.Valid {
				_m.OutputPrice = value.Float64
			}
		case providerpricing.FieldCacheCreationPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_price", values[i])
			} else if value.Valid {
				_m.CacheCreationPrice = value.Float64
			}
		case providerpricing.FieldCacheReadPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_price", values[i])
			} else if value.Valid {
				_m.CacheReadPrice = value.Float64
			}
		case providerpricing.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case providerpricing.FieldEffectiveFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_from", values[i])
			} else if value.Valid {
				_m.EffectiveFrom = value.Time
			}
		case providerpricing.FieldEffectiveTo:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_to", values[i])
			} else if value.Valid {
				_m.EffectiveTo = new(time.Time)
				*_m.EffectiveTo = value.Time
			}
		case providerpricing.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case providerpricing.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case providerpricing.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderPricing.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderPricing) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProviderPricing.
// Note that you need to call ProviderPricing.Unwrap() before calling this method if this ProviderPricing
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderPricing) Update() *ProviderPricingUpdateOne {
	return NewProviderPricingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderPricing entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderPricing) Unwrap() *ProviderPricing {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderPricing is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderPricing) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderPricing(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("billing_mode=")
	builder.WriteString(_m.BillingMode)
	builder.WriteString(", ")
	builder.WriteString("input_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputPrice))
	builder.WriteString(", ")
	builder.WriteString("output_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputPrice))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationPrice))
	builder.WriteString(", ")
	builder.WriteString("cache_read_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadPrice))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("effective_from=")
	builder.WriteString(_m.EffectiveFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EffectiveTo; v != nil {
		builder.WriteString("effective_to=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderPricings is a parsable slice of ProviderPricing.
type ProviderPricings []*ProviderPricing
