// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/teamfundtransfer"
)

// TeamFundTransfer is the model entity for the TeamFundTransfer schema.
type TeamFundTransfer struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID int64 `json:"owner_user_id,omitempty"`
	// MemberUserID holds the value of the "member_user_id" field.
	MemberUserID int64 `json:"member_user_id,omitempty"`
	// Direction holds the value of the "direction" field.
	Direction string `json:"direction,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// OperatorUserID holds the value of the "operator_user_id" field.
	OperatorUserID int64 `json:"operator_user_id,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamFundTransfer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teamfundtransfer.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case teamfundtransfer.FieldID, teamfundtransfer.FieldOwnerUserID, teamfundtransfer.FieldMemberUserID, teamfundtransfer.FieldOperatorUserID:
			values[i] = new(sql.NullInt64)
		case teamfundtransfer.FieldDirection, teamfundtransfer.FieldNote:
			values[i] = new(sql.NullString)
		case teamfundtransfer.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamFundTransfer fields.
func (_m *TeamFundTransfer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teamfundtransfer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case teamfundtransfer.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.Int64
			}
		case teamfundtransfer.FieldMemberUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field member_user_id", values[i])
			} else if value.Valid {
				_m.MemberUserID = value.Int64
			}
		case teamfundtransfer.FieldDirection:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field direction", values[i])
			} else if value.Valid {
				_m.Direction = value.String
			}
		case teamfundtransfer.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case teamfundtransfer.FieldOperatorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_user_id", values[i])
			} else if value.Valid {
				_m.OperatorUserID = value.Int64
			}
		case teamfundtransfer.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case teamfundtransfer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamFundTransfer.
// This includes values selected through modifiers, order, etc.
func (_m *TeamFundTransfer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TeamFundTransfer.
// Note that you need to call TeamFundTransfer.Unwrap() before calling this method if this TeamFundTransfer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeamFundTransfer) Update() *TeamFundTransferUpdateOne {
	return NewTeamFundTransferClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeamFundTransfer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeamFundTransfer) Unwrap() *TeamFundTransfer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TeamFundTransfer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeamFundTransfer) String() string {
	var builder strings.Builder
	builder.WriteString("TeamFundTransfer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	builder.WriteString("member_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemberUserID))
	builder.WriteString(", ")
	builder.WriteString("direction=")
	builder.WriteString(_m.Direction)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("operator_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OperatorUserID))
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TeamFundTransfers is a parsable slice of TeamFundTransfer.
type TeamFundTransfers []*TeamFundTransfer
