// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/teamfundtransfer"
)

// TeamFundTransferCreate is the builder for creating a TeamFundTransfer entity.
type TeamFundTransferCreate struct {
	config
	mutation *TeamFundTransferMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *TeamFundTransferCreate) SetOwnerUserID(v int64) *TeamFundTransferCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetMemberUserID sets the "member_user_id" field.
func (_c *TeamFundTransferCreate) SetMemberUserID(v int64) *TeamFundTransferCreate {
	_c.mutation.SetMemberUserID(v)
	return _c
}

// SetDirection sets the "direction" field.
func (_c *TeamFundTransferCreate) SetDirection(v string) *TeamFundTransferCreate {
	_c.mutation.SetDirection(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *TeamFundTransferCreate) SetAmount(v float64) *TeamFundTransferCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_c *TeamFundTransferCreate) SetOperatorUserID(v int64) *TeamFundTransferCreate {
	_c.mutation.SetOperatorUserID(v)
	return _c
}

// SetNote sets the "note" field.
func (_c *TeamFundTransferCreate) SetNote(v string) *TeamFundTransferCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *TeamFundTransferCreate) SetNillableNote(v *string) *TeamFundTransferCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamFundTransferCreate) SetCreatedAt(v time.Time) *TeamFundTransferCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamFundTransferCreate) SetNillableCreatedAt(v *time.Time) *TeamFundTransferCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the TeamFundTransferMutation object of the builder.
func (_c *TeamFundTransferCreate) Mutation() *TeamFundTransferMutation {
	return _c.mutation
}

// Save creates the TeamFundTransfer in the database.
func (_c *TeamFundTransferCreate) Save(ctx context.Context) (*TeamFundTransfer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamFundTransferCreate) SaveX(ctx context.Context) *TeamFundTransfer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamFundTransferCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamFundTransferCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamFundTransferCreate) defaults() {
	if _, ok := _c.mutation.Note(); !ok {
		v := teamfundtransfer.DefaultNote
		_c.mutation.SetNote(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teamfundtransfer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamFundTransferCreate) check() error {
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "TeamFundTransfer.owner_user_id"`)}
	}
	if _, ok := _c.mutation.MemberUserID(); !ok {
		return &ValidationError{Name: "member_user_id", err: errors.New(`ent: missing required field "TeamFundTransfer.member_user_id"`)}
	}
	if _, ok := _c.mutation.Direction(); !ok {
		return &ValidationError{Name: "direction", err: errors.New(`ent: missing required field "TeamFundTransfer.direction"`)}
	}
	if v, ok := _c.mutation.Direction(); ok {
		if err := teamfundtransfer.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "TeamFundTransfer.direction": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "TeamFundTransfer.amount"`)}
	}
	if _, ok := _c.mutation.OperatorUserID(); !ok {
		return &ValidationError{Name: "operator_user_id", err: errors.New(`ent: missing required field "TeamFundTransfer.operator_user_id"`)}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "TeamFundTransfer.note"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamFundTransfer.created_at"`)}
	}
	return nil
}

func (_c *TeamFundTransferCreate) sqlSave(ctx context.Context) (*TeamFundTransfer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamFundTransferCreate) createSpec() (*TeamFundTransfer, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamFundTransfer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teamfundtransfer.Table, sqlgraph.NewFieldSpec(teamfundtransfer.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(teamfundtransfer.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.MemberUserID(); ok {
		_spec.SetField(teamfundtransfer.FieldMemberUserID, field.TypeInt64, value)
		_node.MemberUserID = value
	}
	if value, ok := _c.mutation.Direction(); ok {
		_spec.SetField(teamfundtransfer.FieldDirection, field.TypeString, value)
		_node.Direction = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(teamfundtransfer.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.OperatorUserID(); ok {
		_spec.SetField(teamfundtransfer.FieldOperatorUserID, field.TypeInt64, value)
		_node.OperatorUserID = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(teamfundtransfer.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teamfundtransfer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamFundTransfer.Create().
//		SetOwnerUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamFundTransferUpsert) {
//			SetOwnerUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamFundTransferCreate) OnConflict(opts ...sql.ConflictOption) *TeamFundTransferUpsertOne {
	_c.conflict = opts
	return &TeamFundTransferUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamFundTransfer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamFundTransferCreate) OnConflictColumns(columns ...string) *TeamFundTransferUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamFundTransferUpsertOne{
		create: _c,
	}
}

type (
	// TeamFundTransferUpsertOne is the builder for "upsert"-ing
	//  one TeamFundTransfer node.
	TeamFundTransferUpsertOne struct {
		create *TeamFundTransferCreate
	}

	// TeamFundTransferUpsert is the "OnConflict" setter.
	TeamFundTransferUpsert struct {
		*sql.UpdateSet
	}
)

// SetOwnerUserID sets the "owner_user_id" field.
func (u *TeamFundTransferUpsert) SetOwnerUserID(v int64) *TeamFundTransferUpsert {
	u.Set(teamfundtransfer.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *TeamFundTransferUpsert) UpdateOwnerUserID() *TeamFundTransferUpsert {
	u.SetExcluded(teamfundtransfer.FieldOwnerUserID)
	return u
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *TeamFundTransferUpsert) AddOwnerUserID(v int64) *TeamFundTransferUpsert {
	u.Add(teamfundtransfer.FieldOwnerUserID, v)
	return u
}

// SetMemberUserID sets the "member_user_id" field.
func (u *TeamFundTransferUpsert) SetMemberUserID(v int64) *TeamFundTransferUpsert {
	u.Set(teamfundtransfer.FieldMemberUserID, v)
	return u
}

// UpdateMemberUserID sets the "member_user_id" field to the value that was provided on create.
func (u *TeamFundTransferUpsert) UpdateMemberUserID() *TeamFundTransferUpsert {
	u.SetExcluded(teamfundtransfer.FieldMemberUserID)
	return u
}

// AddMemberUserID adds v to the "member_user_id" field.
func (u *TeamFundTransferUpsert) AddMemberUserID(v int64) *TeamFundTransferUpsert {
	u.Add(teamfundtransfer.FieldMemberUserID, v)
	return u
}

// SetDirection sets the "direction" field.
func (u *TeamFundTransferUpsert) SetDirection(v string) *TeamFundTransferUpsert {
	u.Set(teamfundtransfer.FieldDirection, v)
	return u
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *TeamFundTransferUpsert) UpdateDirection() *TeamFundTransferUpsert {
	u.SetExcluded(teamfundtransfer.FieldDirection)
	return u
}

// SetAmount sets the "amount" field.
func (u *TeamFundTransferUpsert) SetAmount(v float64) *TeamFundTransferUpsert {
	u.Set(teamfundtransfer.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TeamFundTransferUpsert) UpdateAmount() *TeamFundTransferUpsert {
	u.SetExcluded(teamfundtransfer.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *TeamFundTransferUpsert) AddAmount(v float64) *TeamFundTransferUpsert {
	u.Add(teamfundtransfer.FieldAmount, v)
	return u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *TeamFundTransferUpsert) SetOperatorUserID(v int64) *TeamFundTransferUpsert {
	u.Set(teamfundtransfer.FieldOperatorUserID, v)
	return u
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *TeamFundTransferUpsert) UpdateOperatorUserID() *TeamFundTransferUpsert {
	u.SetExcluded(teamfundtransfer.FieldOperatorUserID)
	return u
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *TeamFundTransferUpsert) AddOperatorUserID(v int64) *TeamFundTransferUpsert {
	u.Add(teamfundtransfer.FieldOperatorUserID, v)
	return u
}

// SetNote sets the "note" field.
func (u *TeamFundTransferUpsert) SetNote(v string) *TeamFundTransferUpsert {
	u.Set(teamfundtransfer.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *TeamFundTransferUpsert) UpdateNote() *TeamFundTransferUpsert {
	u.SetExcluded(teamfundtransfer.FieldNote)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamFundTransfer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamFundTransferUpsertOne) UpdateNewValues() *TeamFundTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(teamfundtransfer.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamFundTransfer.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamFundTransferUpsertOne) Ignore() *TeamFundTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamFundTransferUpsertOne) DoNothing() *TeamFundTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamFundTransferCreate.OnConflict
// documentation for more info.
func (u *TeamFundTransferUpsertOne) Update(set func(*TeamFundTransferUpsert)) *TeamFundTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamFundTransferUpsert{UpdateSet: update})
	}))
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *TeamFundTransferUpsertOne) SetOwnerUserID(v int64) *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *TeamFundTransferUpsertOne) AddOwnerUserID(v int64) *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *TeamFundTransferUpsertOne) UpdateOwnerUserID() *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetMemberUserID sets the "member_user_id" field.
func (u *TeamFundTransferUpsertOne) SetMemberUserID(v int64) *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.SetMemberUserID(v)
	})
}

// AddMemberUserID adds v to the "member_user_id" field.
func (u *TeamFundTransferUpsertOne) AddMemberUserID(v int64) *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.AddMemberUserID(v)
	})
}

// UpdateMemberUserID sets the "member_user_id" field to the value that was provided on create.
func (u *TeamFundTransferUpsertOne) UpdateMemberUserID() *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.UpdateMemberUserID()
	})
}

// SetDirection sets the "direction" field.
func (u *TeamFundTransferUpsertOne) SetDirection(v string) *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.SetDirection(v)
	})
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *TeamFundTransferUpsertOne) UpdateDirection() *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.UpdateDirection()
	})
}

// SetAmount sets the "amount" field.
func (u *TeamFundTransferUpsertOne) SetAmount(v float64) *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TeamFundTransferUpsertOne) AddAmount(v float64) *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TeamFundTransferUpsertOne) UpdateAmount() *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.UpdateAmount()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *TeamFundTransferUpsertOne) SetOperatorUserID(v int64) *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *TeamFundTransferUpsertOne) AddOperatorUserID(v int64) *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *TeamFundTransferUpsertOne) UpdateOperatorUserID() *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.UpdateOperatorUserID()
	})
}

// SetNote sets the "note" field.
func (u *TeamFundTransferUpsertOne) SetNote(v string) *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *TeamFundTransferUpsertOne) UpdateNote() *TeamFundTransferUpsertOne {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.UpdateNote()
	})
}

// Exec executes the query.
func (u *TeamFundTransferUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamFundTransferCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamFundTransferUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamFundTransferUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamFundTransferUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamFundTransferCreateBulk is the builder for creating many TeamFundTransfer entities in bulk.
type TeamFundTransferCreateBulk struct {
	config
	err      error
	builders []*TeamFundTransferCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamFundTransfer entities in the database.
func (_c *TeamFundTransferCreateBulk) Save(ctx context.Context) ([]*TeamFundTransfer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamFundTransfer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamFundTransferMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamFundTransferCreateBulk) SaveX(ctx context.Context) []*TeamFundTransfer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamFundTransferCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamFundTransferCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamFundTransfer.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamFundTransferUpsert) {
//			SetOwnerUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamFundTransferCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamFundTransferUpsertBulk {
	_c.conflict = opts
	return &TeamFundTransferUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamFundTransfer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamFundTransferCreateBulk) OnConflictColumns(columns ...string) *TeamFundTransferUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamFundTransferUpsertBulk{
		create: _c,
	}
}

// TeamFundTransferUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamFundTransfer nodes.
type TeamFundTransferUpsertBulk struct {
	create *TeamFundTransferCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamFundTransfer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamFundTransferUpsertBulk) UpdateNewValues() *TeamFundTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(teamfundtransfer.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamFundTransfer.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamFundTransferUpsertBulk) Ignore() *TeamFundTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamFundTransferUpsertBulk) DoNothing() *TeamFundTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamFundTransferCreateBulk.OnConflict
// documentation for more info.
func (u *TeamFundTransferUpsertBulk) Update(set func(*TeamFundTransferUpsert)) *TeamFundTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamFundTransferUpsert{UpdateSet: update})
	}))
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *TeamFundTransferUpsertBulk) SetOwnerUserID(v int64) *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *TeamFundTransferUpsertBulk) AddOwnerUserID(v int64) *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *TeamFundTransferUpsertBulk) UpdateOwnerUserID() *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetMemberUserID sets the "member_user_id" field.
func (u *TeamFundTransferUpsertBulk) SetMemberUserID(v int64) *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.SetMemberUserID(v)
	})
}

// AddMemberUserID adds v to the "member_user_id" field.
func (u *TeamFundTransferUpsertBulk) AddMemberUserID(v int64) *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.AddMemberUserID(v)
	})
}

// UpdateMemberUserID sets the "member_user_id" field to the value that was provided on create.
func (u *TeamFundTransferUpsertBulk) UpdateMemberUserID() *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.UpdateMemberUserID()
	})
}

// SetDirection sets the "direction" field.
func (u *TeamFundTransferUpsertBulk) SetDirection(v string) *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.SetDirection(v)
	})
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *TeamFundTransferUpsertBulk) UpdateDirection() *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.UpdateDirection()
	})
}

// SetAmount sets the "amount" field.
func (u *TeamFundTransferUpsertBulk) SetAmount(v float64) *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TeamFundTransferUpsertBulk) AddAmount(v float64) *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TeamFundTransferUpsertBulk) UpdateAmount() *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.UpdateAmount()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *TeamFundTransferUpsertBulk) SetOperatorUserID(v int64) *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *TeamFundTransferUpsertBulk) AddOperatorUserID(v int64) *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *TeamFundTransferUpsertBulk) UpdateOperatorUserID() *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.UpdateOperatorUserID()
	})
}

// SetNote sets the "note" field.
func (u *TeamFundTransferUpsertBulk) SetNote(v string) *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *TeamFundTransferUpsertBulk) UpdateNote() *TeamFundTransferUpsertBulk {
	return u.Update(func(s *TeamFundTransferUpsert) {
		s.UpdateNote()
	})
}

// Exec executes the query.
func (u *TeamFundTransferUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamFundTransferCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamFundTransferCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamFundTransferUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
