// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/teammember"
)

// TeamMemberUpdate is the builder for updating TeamMember entities.
type TeamMemberUpdate struct {
	config
	hooks    []Hook
	mutation *TeamMemberMutation
}

// Where appends a list predicates to the TeamMemberUpdate builder.
func (_u *TeamMemberUpdate) Where(ps ...predicate.TeamMember) *TeamMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamMemberUpdate) SetUpdatedAt(v time.Time) *TeamMemberUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *TeamMemberUpdate) SetOwnerUserID(v int64) *TeamMemberUpdate {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableOwnerUserID(v *int64) *TeamMemberUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *TeamMemberUpdate) AddOwnerUserID(v int64) *TeamMemberUpdate {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetMemberUserID sets the "member_user_id" field.
func (_u *TeamMemberUpdate) SetMemberUserID(v int64) *TeamMemberUpdate {
	_u.mutation.ResetMemberUserID()
	_u.mutation.SetMemberUserID(v)
	return _u
}

// SetNillableMemberUserID sets the "member_user_id" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableMemberUserID(v *int64) *TeamMemberUpdate {
	if v != nil {
		_u.SetMemberUserID(*v)
	}
	return _u
}

// AddMemberUserID adds value to the "member_user_id" field.
func (_u *TeamMemberUpdate) AddMemberUserID(v int64) *TeamMemberUpdate {
	_u.mutation.AddMemberUserID(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *TeamMemberUpdate) SetRole(v string) *TeamMemberUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableRole(v *string) *TeamMemberUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamMemberUpdate) SetStatus(v string) *TeamMemberUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableStatus(v *string) *TeamMemberUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *TeamMemberUpdate) SetDepartmentID(v int64) *TeamMemberUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableDepartmentID(v *int64) *TeamMemberUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *TeamMemberUpdate) AddDepartmentID(v int64) *TeamMemberUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *TeamMemberUpdate) ClearDepartmentID() *TeamMemberUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetQuotaMode sets the "quota_mode" field.
func (_u *TeamMemberUpdate) SetQuotaMode(v string) *TeamMemberUpdate {
	_u.mutation.SetQuotaMode(v)
	return _u
}

// SetNillableQuotaMode sets the "quota_mode" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableQuotaMode(v *string) *TeamMemberUpdate {
	if v != nil {
		_u.SetQuotaMode(*v)
	}
	return _u
}

// SetAutoTopupThresholdUsd sets the "auto_topup_threshold_usd" field.
func (_u *TeamMemberUpdate) SetAutoTopupThresholdUsd(v float64) *TeamMemberUpdate {
	_u.mutation.ResetAutoTopupThresholdUsd()
	_u.mutation.SetAutoTopupThresholdUsd(v)
	return _u
}

// SetNillableAutoTopupThresholdUsd sets the "auto_topup_threshold_usd" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableAutoTopupThresholdUsd(v *float64) *TeamMemberUpdate {
	if v != nil {
		_u.SetAutoTopupThresholdUsd(*v)
	}
	return _u
}

// AddAutoTopupThresholdUsd adds value to the "auto_topup_threshold_usd" field.
func (_u *TeamMemberUpdate) AddAutoTopupThresholdUsd(v float64) *TeamMemberUpdate {
	_u.mutation.AddAutoTopupThresholdUsd(v)
	return _u
}

// ClearAutoTopupThresholdUsd clears the value of the "auto_topup_threshold_usd" field.
func (_u *TeamMemberUpdate) ClearAutoTopupThresholdUsd() *TeamMemberUpdate {
	_u.mutation.ClearAutoTopupThresholdUsd()
	return _u
}

// SetAutoTopupTargetUsd sets the "auto_topup_target_usd" field.
func (_u *TeamMemberUpdate) SetAutoTopupTargetUsd(v float64) *TeamMemberUpdate {
	_u.mutation.ResetAutoTopupTargetUsd()
	_u.mutation.SetAutoTopupTargetUsd(v)
	return _u
}

// SetNillableAutoTopupTargetUsd sets the "auto_topup_target_usd" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableAutoTopupTargetUsd(v *float64) *TeamMemberUpdate {
	if v != nil {
		_u.SetAutoTopupTargetUsd(*v)
	}
	return _u
}

// AddAutoTopupTargetUsd adds value to the "auto_topup_target_usd" field.
func (_u *TeamMemberUpdate) AddAutoTopupTargetUsd(v float64) *TeamMemberUpdate {
	_u.mutation.AddAutoTopupTargetUsd(v)
	return _u
}

// ClearAutoTopupTargetUsd clears the value of the "auto_topup_target_usd" field.
func (_u *TeamMemberUpdate) ClearAutoTopupTargetUsd() *TeamMemberUpdate {
	_u.mutation.ClearAutoTopupTargetUsd()
	return _u
}

// SetGrantedNetUsd sets the "granted_net_usd" field.
func (_u *TeamMemberUpdate) SetGrantedNetUsd(v float64) *TeamMemberUpdate {
	_u.mutation.ResetGrantedNetUsd()
	_u.mutation.SetGrantedNetUsd(v)
	return _u
}

// SetNillableGrantedNetUsd sets the "granted_net_usd" field if the given value is not nil.
func (_u *TeamMemberUpdate) SetNillableGrantedNetUsd(v *float64) *TeamMemberUpdate {
	if v != nil {
		_u.SetGrantedNetUsd(*v)
	}
	return _u
}

// AddGrantedNetUsd adds value to the "granted_net_usd" field.
func (_u *TeamMemberUpdate) AddGrantedNetUsd(v float64) *TeamMemberUpdate {
	_u.mutation.AddGrantedNetUsd(v)
	return _u
}

// Mutation returns the TeamMemberMutation object of the builder.
func (_u *TeamMemberUpdate) Mutation() *TeamMemberMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamMemberUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamMemberUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teammember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamMemberUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := teammember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "TeamMember.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := teammember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamMember.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaMode(); ok {
		if err := teammember.QuotaModeValidator(v); err != nil {
			return &ValidationError{Name: "quota_mode", err: fmt.Errorf(`ent: validator failed for field "TeamMember.quota_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *TeamMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teammember.Table, teammember.Columns, sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teammember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(teammember.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(teammember.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MemberUserID(); ok {
		_spec.SetField(teammember.FieldMemberUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMemberUserID(); ok {
		_spec.AddField(teammember.FieldMemberUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(teammember.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teammember.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(teammember.FieldDepartmentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(teammember.FieldDepartmentID, field.TypeInt64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(teammember.FieldDepartmentID, field.TypeInt64)
	}
	if value, ok := _u.mutation.QuotaMode(); ok {
		_spec.SetField(teammember.FieldQuotaMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AutoTopupThresholdUsd(); ok {
		_spec.SetField(teammember.FieldAutoTopupThresholdUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAutoTopupThresholdUsd(); ok {
		_spec.AddField(teammember.FieldAutoTopupThresholdUsd, field.TypeFloat64, value)
	}
	if _u.mutation.AutoTopupThresholdUsdCleared() {
		_spec.ClearField(teammember.FieldAutoTopupThresholdUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AutoTopupTargetUsd(); ok {
		_spec.SetField(teammember.FieldAutoTopupTargetUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAutoTopupTargetUsd(); ok {
		_spec.AddField(teammember.FieldAutoTopupTargetUsd, field.TypeFloat64, value)
	}
	if _u.mutation.AutoTopupTargetUsdCleared() {
		_spec.ClearField(teammember.FieldAutoTopupTargetUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.GrantedNetUsd(); ok {
		_spec.SetField(teammember.FieldGrantedNetUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrantedNetUsd(); ok {
		_spec.AddField(teammember.FieldGrantedNetUsd, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teammember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamMemberUpdateOne is the builder for updating a single TeamMember entity.
type TeamMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamMemberMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamMemberUpdateOne) SetUpdatedAt(v time.Time) *TeamMemberUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *TeamMemberUpdateOne) SetOwnerUserID(v int64) *TeamMemberUpdateOne {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableOwnerUserID(v *int64) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *TeamMemberUpdateOne) AddOwnerUserID(v int64) *TeamMemberUpdateOne {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetMemberUserID sets the "member_user_id" field.
func (_u *TeamMemberUpdateOne) SetMemberUserID(v int64) *TeamMemberUpdateOne {
	_u.mutation.ResetMemberUserID()
	_u.mutation.SetMemberUserID(v)
	return _u
}

// SetNillableMemberUserID sets the "member_user_id" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableMemberUserID(v *int64) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetMemberUserID(*v)
	}
	return _u
}

// AddMemberUserID adds value to the "member_user_id" field.
func (_u *TeamMemberUpdateOne) AddMemberUserID(v int64) *TeamMemberUpdateOne {
	_u.mutation.AddMemberUserID(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *TeamMemberUpdateOne) SetRole(v string) *TeamMemberUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableRole(v *string) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamMemberUpdateOne) SetStatus(v string) *TeamMemberUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableStatus(v *string) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *TeamMemberUpdateOne) SetDepartmentID(v int64) *TeamMemberUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableDepartmentID(v *int64) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *TeamMemberUpdateOne) AddDepartmentID(v int64) *TeamMemberUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *TeamMemberUpdateOne) ClearDepartmentID() *TeamMemberUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetQuotaMode sets the "quota_mode" field.
func (_u *TeamMemberUpdateOne) SetQuotaMode(v string) *TeamMemberUpdateOne {
	_u.mutation.SetQuotaMode(v)
	return _u
}

// SetNillableQuotaMode sets the "quota_mode" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableQuotaMode(v *string) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetQuotaMode(*v)
	}
	return _u
}

// SetAutoTopupThresholdUsd sets the "auto_topup_threshold_usd" field.
func (_u *TeamMemberUpdateOne) SetAutoTopupThresholdUsd(v float64) *TeamMemberUpdateOne {
	_u.mutation.ResetAutoTopupThresholdUsd()
	_u.mutation.SetAutoTopupThresholdUsd(v)
	return _u
}

// SetNillableAutoTopupThresholdUsd sets the "auto_topup_threshold_usd" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableAutoTopupThresholdUsd(v *float64) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetAutoTopupThresholdUsd(*v)
	}
	return _u
}

// AddAutoTopupThresholdUsd adds value to the "auto_topup_threshold_usd" field.
func (_u *TeamMemberUpdateOne) AddAutoTopupThresholdUsd(v float64) *TeamMemberUpdateOne {
	_u.mutation.AddAutoTopupThresholdUsd(v)
	return _u
}

// ClearAutoTopupThresholdUsd clears the value of the "auto_topup_threshold_usd" field.
func (_u *TeamMemberUpdateOne) ClearAutoTopupThresholdUsd() *TeamMemberUpdateOne {
	_u.mutation.ClearAutoTopupThresholdUsd()
	return _u
}

// SetAutoTopupTargetUsd sets the "auto_topup_target_usd" field.
func (_u *TeamMemberUpdateOne) SetAutoTopupTargetUsd(v float64) *TeamMemberUpdateOne {
	_u.mutation.ResetAutoTopupTargetUsd()
	_u.mutation.SetAutoTopupTargetUsd(v)
	return _u
}

// SetNillableAutoTopupTargetUsd sets the "auto_topup_target_usd" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableAutoTopupTargetUsd(v *float64) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetAutoTopupTargetUsd(*v)
	}
	return _u
}

// AddAutoTopupTargetUsd adds value to the "auto_topup_target_usd" field.
func (_u *TeamMemberUpdateOne) AddAutoTopupTargetUsd(v float64) *TeamMemberUpdateOne {
	_u.mutation.AddAutoTopupTargetUsd(v)
	return _u
}

// ClearAutoTopupTargetUsd clears the value of the "auto_topup_target_usd" field.
func (_u *TeamMemberUpdateOne) ClearAutoTopupTargetUsd() *TeamMemberUpdateOne {
	_u.mutation.ClearAutoTopupTargetUsd()
	return _u
}

// SetGrantedNetUsd sets the "granted_net_usd" field.
func (_u *TeamMemberUpdateOne) SetGrantedNetUsd(v float64) *TeamMemberUpdateOne {
	_u.mutation.ResetGrantedNetUsd()
	_u.mutation.SetGrantedNetUsd(v)
	return _u
}

// SetNillableGrantedNetUsd sets the "granted_net_usd" field if the given value is not nil.
func (_u *TeamMemberUpdateOne) SetNillableGrantedNetUsd(v *float64) *TeamMemberUpdateOne {
	if v != nil {
		_u.SetGrantedNetUsd(*v)
	}
	return _u
}

// AddGrantedNetUsd adds value to the "granted_net_usd" field.
func (_u *TeamMemberUpdateOne) AddGrantedNetUsd(v float64) *TeamMemberUpdateOne {
	_u.mutation.AddGrantedNetUsd(v)
	return _u
}

// Mutation returns the TeamMemberMutation object of the builder.
func (_u *TeamMemberUpdateOne) Mutation() *TeamMemberMutation {
	return _u.mutation
}

// Where appends a list predicates to the TeamMemberUpdate builder.
func (_u *TeamMemberUpdateOne) Where(ps ...predicate.TeamMember) *TeamMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamMemberUpdateOne) Select(field string, fields ...string) *TeamMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamMember entity.
func (_u *TeamMemberUpdateOne) Save(ctx context.Context) (*TeamMember, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamMemberUpdateOne) SaveX(ctx context.Context) *TeamMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamMemberUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teammember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamMemberUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := teammember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "TeamMember.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := teammember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamMember.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaMode(); ok {
		if err := teammember.QuotaModeValidator(v); err != nil {
			return &ValidationError{Name: "quota_mode", err: fmt.Errorf(`ent: validator failed for field "TeamMember.quota_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *TeamMemberUpdateOne) sqlSave(ctx context.Context) (_node *TeamMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teammember.Table, teammember.Columns, sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teammember.FieldID)
		for _, f := range fields {
			if !teammember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teammember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teammember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(teammember.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(teammember.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MemberUserID(); ok {
		_spec.SetField(teammember.FieldMemberUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMemberUserID(); ok {
		_spec.AddField(teammember.FieldMemberUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(teammember.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teammember.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(teammember.FieldDepartmentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(teammember.FieldDepartmentID, field.TypeInt64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(teammember.FieldDepartmentID, field.TypeInt64)
	}
	if value, ok := _u.mutation.QuotaMode(); ok {
		_spec.SetField(teammember.FieldQuotaMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AutoTopupThresholdUsd(); ok {
		_spec.SetField(teammember.FieldAutoTopupThresholdUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAutoTopupThresholdUsd(); ok {
		_spec.AddField(teammember.FieldAutoTopupThresholdUsd, field.TypeFloat64, value)
	}
	if _u.mutation.AutoTopupThresholdUsdCleared() {
		_spec.ClearField(teammember.FieldAutoTopupThresholdUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AutoTopupTargetUsd(); ok {
		_spec.SetField(teammember.FieldAutoTopupTargetUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAutoTopupTargetUsd(); ok {
		_spec.AddField(teammember.FieldAutoTopupTargetUsd, field.TypeFloat64, value)
	}
	if _u.mutation.AutoTopupTargetUsdCleared() {
		_spec.ClearField(teammember.FieldAutoTopupTargetUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.GrantedNetUsd(); ok {
		_spec.SetField(teammember.FieldGrantedNetUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrantedNetUsd(); ok {
		_spec.AddField(teammember.FieldGrantedNetUsd, field.TypeFloat64, value)
	}
	_node = &TeamMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teammember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
