// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/teaminvitation"
)

// TeamInvitation is the model entity for the TeamInvitation schema.
type TeamInvitation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID int64 `json:"owner_user_id,omitempty"`
	// InvitedEmail holds the value of the "invited_email" field.
	InvitedEmail string `json:"invited_email,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// LastSentAt holds the value of the "last_sent_at" field.
	LastSentAt time.Time `json:"last_sent_at,omitempty"`
	// DepartmentID holds the value of the "department_id" field.
	DepartmentID *int64 `json:"department_id,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// QuotaMode holds the value of the "quota_mode" field.
	QuotaMode string `json:"quota_mode,omitempty"`
	// InitialGrantUsd holds the value of the "initial_grant_usd" field.
	InitialGrantUsd *float64 `json:"initial_grant_usd,omitempty"`
	// AcceptedByUserID holds the value of the "accepted_by_user_id" field.
	AcceptedByUserID *int64 `json:"accepted_by_user_id,omitempty"`
	// AcceptedAt holds the value of the "accepted_at" field.
	AcceptedAt   *time.Time `json:"accepted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamInvitation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teaminvitation.FieldInitialGrantUsd:
			values[i] = new(sql.NullFloat64)
		case teaminvitation.FieldID, teaminvitation.FieldOwnerUserID, teaminvitation.FieldDepartmentID, teaminvitation.FieldAcceptedByUserID:
			values[i] = new(sql.NullInt64)
		case teaminvitation.FieldInvitedEmail, teaminvitation.FieldToken, teaminvitation.FieldStatus, teaminvitation.FieldRole, teaminvitation.FieldQuotaMode:
			values[i] = new(sql.NullString)
		case teaminvitation.FieldCreatedAt, teaminvitation.FieldUpdatedAt, teaminvitation.FieldExpiresAt, teaminvitation.FieldLastSentAt, teaminvitation.FieldAcceptedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamInvitation fields.
func (_m *TeamInvitation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teaminvitation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case teaminvitation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case teaminvitation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case teaminvitation.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.Int64
			}
		case teaminvitation.FieldInvitedEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invited_email", values[i])
			} else if value.Valid {
				_m.InvitedEmail = value.String
			}
		case teaminvitation.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case teaminvitation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case teaminvitation.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case teaminvitation.FieldLastSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sent_at", values[i])
			} else if value.Valid {
				_m.LastSentAt = value.Time
			}
		case teaminvitation.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				_m.DepartmentID = new(int64)
				*_m.DepartmentID = value.Int64
			}
		case teaminvitation.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case teaminvitation.FieldQuotaMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quota_mode", values[i])
			} else if value.Valid {
				_m.QuotaMode = value.String
			}
		case teaminvitation.FieldInitialGrantUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field initial_grant_usd", values[i])
			} else if value.Valid {
				_m.InitialGrantUsd = new(float64)
				*_m.InitialGrantUsd = value.Float64
			}
		case teaminvitation.FieldAcceptedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field accepted_by_user_id", values[i])
			} else if value.Valid {
				_m.AcceptedByUserID = new(int64)
				*_m.AcceptedByUserID = value.Int64
			}
		case teaminvitation.FieldAcceptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field accepted_at", values[i])
			} else if value.Valid {
				_m.AcceptedAt = new(time.Time)
				*_m.AcceptedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamInvitation.
// This includes values selected through modifiers, order, etc.
func (_m *TeamInvitation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TeamInvitation.
// Note that you need to call TeamInvitation.Unwrap() before calling this method if this TeamInvitation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeamInvitation) Update() *TeamInvitationUpdateOne {
	return NewTeamInvitationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeamInvitation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeamInvitation) Unwrap() *TeamInvitation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TeamInvitation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeamInvitation) String() string {
	var builder strings.Builder
	builder.WriteString("TeamInvitation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	builder.WriteString("invited_email=")
	builder.WriteString(_m.InvitedEmail)
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_sent_at=")
	builder.WriteString(_m.LastSentAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DepartmentID; v != nil {
		builder.WriteString("department_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("quota_mode=")
	builder.WriteString(_m.QuotaMode)
	builder.WriteString(", ")
	if v := _m.InitialGrantUsd; v != nil {
		builder.WriteString("initial_grant_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AcceptedByUserID; v != nil {
		builder.WriteString("accepted_by_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AcceptedAt; v != nil {
		builder.WriteString("accepted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// TeamInvitations is a parsable slice of TeamInvitation.
type TeamInvitations []*TeamInvitation
