// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/teammember"
)

// TeamMemberCreate is the builder for creating a TeamMember entity.
type TeamMemberCreate struct {
	config
	mutation *TeamMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamMemberCreate) SetCreatedAt(v time.Time) *TeamMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableCreatedAt(v *time.Time) *TeamMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TeamMemberCreate) SetUpdatedAt(v time.Time) *TeamMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableUpdatedAt(v *time.Time) *TeamMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *TeamMemberCreate) SetOwnerUserID(v int64) *TeamMemberCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetMemberUserID sets the "member_user_id" field.
func (_c *TeamMemberCreate) SetMemberUserID(v int64) *TeamMemberCreate {
	_c.mutation.SetMemberUserID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *TeamMemberCreate) SetRole(v string) *TeamMemberCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableRole(v *string) *TeamMemberCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TeamMemberCreate) SetStatus(v string) *TeamMemberCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableStatus(v *string) *TeamMemberCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDepartmentID sets the "department_id" field.
func (_c *TeamMemberCreate) SetDepartmentID(v int64) *TeamMemberCreate {
	_c.mutation.SetDepartmentID(v)
	return _c
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableDepartmentID(v *int64) *TeamMemberCreate {
	if v != nil {
		_c.SetDepartmentID(*v)
	}
	return _c
}

// SetQuotaMode sets the "quota_mode" field.
func (_c *TeamMemberCreate) SetQuotaMode(v string) *TeamMemberCreate {
	_c.mutation.SetQuotaMode(v)
	return _c
}

// SetNillableQuotaMode sets the "quota_mode" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableQuotaMode(v *string) *TeamMemberCreate {
	if v != nil {
		_c.SetQuotaMode(*v)
	}
	return _c
}

// SetAutoTopupThresholdUsd sets the "auto_topup_threshold_usd" field.
func (_c *TeamMemberCreate) SetAutoTopupThresholdUsd(v float64) *TeamMemberCreate {
	_c.mutation.SetAutoTopupThresholdUsd(v)
	return _c
}

// SetNillableAutoTopupThresholdUsd sets the "auto_topup_threshold_usd" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableAutoTopupThresholdUsd(v *float64) *TeamMemberCreate {
	if v != nil {
		_c.SetAutoTopupThresholdUsd(*v)
	}
	return _c
}

// SetAutoTopupTargetUsd sets the "auto_topup_target_usd" field.
func (_c *TeamMemberCreate) SetAutoTopupTargetUsd(v float64) *TeamMemberCreate {
	_c.mutation.SetAutoTopupTargetUsd(v)
	return _c
}

// SetNillableAutoTopupTargetUsd sets the "auto_topup_target_usd" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableAutoTopupTargetUsd(v *float64) *TeamMemberCreate {
	if v != nil {
		_c.SetAutoTopupTargetUsd(*v)
	}
	return _c
}

// SetGrantedNetUsd sets the "granted_net_usd" field.
func (_c *TeamMemberCreate) SetGrantedNetUsd(v float64) *TeamMemberCreate {
	_c.mutation.SetGrantedNetUsd(v)
	return _c
}

// SetNillableGrantedNetUsd sets the "granted_net_usd" field if the given value is not nil.
func (_c *TeamMemberCreate) SetNillableGrantedNetUsd(v *float64) *TeamMemberCreate {
	if v != nil {
		_c.SetGrantedNetUsd(*v)
	}
	return _c
}

// Mutation returns the TeamMemberMutation object of the builder.
func (_c *TeamMemberCreate) Mutation() *TeamMemberMutation {
	return _c.mutation
}

// Save creates the TeamMember in the database.
func (_c *TeamMemberCreate) Save(ctx context.Context) (*TeamMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamMemberCreate) SaveX(ctx context.Context) *TeamMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamMemberCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teammember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := teammember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := teammember.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := teammember.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.QuotaMode(); !ok {
		v := teammember.DefaultQuotaMode
		_c.mutation.SetQuotaMode(v)
	}
	if _, ok := _c.mutation.GrantedNetUsd(); !ok {
		v := teammember.DefaultGrantedNetUsd
		_c.mutation.SetGrantedNetUsd(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamMemberCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamMember.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TeamMember.updated_at"`)}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "TeamMember.owner_user_id"`)}
	}
	if _, ok := _c.mutation.MemberUserID(); !ok {
		return &ValidationError{Name: "member_user_id", err: errors.New(`ent: missing required field "TeamMember.member_user_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "TeamMember.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := teammember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "TeamMember.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TeamMember.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := teammember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamMember.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuotaMode(); !ok {
		return &ValidationError{Name: "quota_mode", err: errors.New(`ent: missing required field "TeamMember.quota_mode"`)}
	}
	if v, ok := _c.mutation.QuotaMode(); ok {
		if err := teammember.QuotaModeValidator(v); err != nil {
			return &ValidationError{Name: "quota_mode", err: fmt.Errorf(`ent: validator failed for field "TeamMember.quota_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GrantedNetUsd(); !ok {
		return &ValidationError{Name: "granted_net_usd", err: errors.New(`ent: missing required field "TeamMember.granted_net_usd"`)}
	}
	return nil
}

func (_c *TeamMemberCreate) sqlSave(ctx context.Context) (*TeamMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamMemberCreate) createSpec() (*TeamMember, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teammember.Table, sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teammember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(teammember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(teammember.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.MemberUserID(); ok {
		_spec.SetField(teammember.FieldMemberUserID, field.TypeInt64, value)
		_node.MemberUserID = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(teammember.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(teammember.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DepartmentID(); ok {
		_spec.SetField(teammember.FieldDepartmentID, field.TypeInt64, value)
		_node.DepartmentID = &value
	}
	if value, ok := _c.mutation.QuotaMode(); ok {
		_spec.SetField(teammember.FieldQuotaMode, field.TypeString, value)
		_node.QuotaMode = value
	}
	if value, ok := _c.mutation.AutoTopupThresholdUsd(); ok {
		_spec.SetField(teammember.FieldAutoTopupThresholdUsd, field.TypeFloat64, value)
		_node.AutoTopupThresholdUsd = &value
	}
	if value, ok := _c.mutation.AutoTopupTargetUsd(); ok {
		_spec.SetField(teammember.FieldAutoTopupTargetUsd, field.TypeFloat64, value)
		_node.AutoTopupTargetUsd = &value
	}
	if value, ok := _c.mutation.GrantedNetUsd(); ok {
		_spec.SetField(teammember.FieldGrantedNetUsd, field.TypeFloat64, value)
		_node.GrantedNetUsd = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamMember.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamMemberCreate) OnConflict(opts ...sql.ConflictOption) *TeamMemberUpsertOne {
	_c.conflict = opts
	return &TeamMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamMemberCreate) OnConflictColumns(columns ...string) *TeamMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamMemberUpsertOne{
		create: _c,
	}
}

type (
	// TeamMemberUpsertOne is the builder for "upsert"-ing
	//  one TeamMember node.
	TeamMemberUpsertOne struct {
		create *TeamMemberCreate
	}

	// TeamMemberUpsert is the "OnConflict" setter.
	TeamMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamMemberUpsert) SetUpdatedAt(v time.Time) *TeamMemberUpsert {
	u.Set(teammember.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateUpdatedAt() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldUpdatedAt)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *TeamMemberUpsert) SetOwnerUserID(v int64) *TeamMemberUpsert {
	u.Set(teammember.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateOwnerUserID() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldOwnerUserID)
	return u
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *TeamMemberUpsert) AddOwnerUserID(v int64) *TeamMemberUpsert {
	u.Add(teammember.FieldOwnerUserID, v)
	return u
}

// SetMemberUserID sets the "member_user_id" field.
func (u *TeamMemberUpsert) SetMemberUserID(v int64) *TeamMemberUpsert {
	u.Set(teammember.FieldMemberUserID, v)
	return u
}

// UpdateMemberUserID sets the "member_user_id" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateMemberUserID() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldMemberUserID)
	return u
}

// AddMemberUserID adds v to the "member_user_id" field.
func (u *TeamMemberUpsert) AddMemberUserID(v int64) *TeamMemberUpsert {
	u.Add(teammember.FieldMemberUserID, v)
	return u
}

// SetRole sets the "role" field.
func (u *TeamMemberUpsert) SetRole(v string) *TeamMemberUpsert {
	u.Set(teammember.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateRole() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldRole)
	return u
}

// SetStatus sets the "status" field.
func (u *TeamMemberUpsert) SetStatus(v string) *TeamMemberUpsert {
	u.Set(teammember.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateStatus() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldStatus)
	return u
}

// SetDepartmentID sets the "department_id" field.
func (u *TeamMemberUpsert) SetDepartmentID(v int64) *TeamMemberUpsert {
	u.Set(teammember.FieldDepartmentID, v)
	return u
}

// UpdateDepartmentID sets the "department_id" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateDepartmentID() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldDepartmentID)
	return u
}

// AddDepartmentID adds v to the "department_id" field.
func (u *TeamMemberUpsert) AddDepartmentID(v int64) *TeamMemberUpsert {
	u.Add(teammember.FieldDepartmentID, v)
	return u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (u *TeamMemberUpsert) ClearDepartmentID() *TeamMemberUpsert {
	u.SetNull(teammember.FieldDepartmentID)
	return u
}

// SetQuotaMode sets the "quota_mode" field.
func (u *TeamMemberUpsert) SetQuotaMode(v string) *TeamMemberUpsert {
	u.Set(teammember.FieldQuotaMode, v)
	return u
}

// UpdateQuotaMode sets the "quota_mode" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateQuotaMode() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldQuotaMode)
	return u
}

// SetAutoTopupThresholdUsd sets the "auto_topup_threshold_usd" field.
func (u *TeamMemberUpsert) SetAutoTopupThresholdUsd(v float64) *TeamMemberUpsert {
	u.Set(teammember.FieldAutoTopupThresholdUsd, v)
	return u
}

// UpdateAutoTopupThresholdUsd sets the "auto_topup_threshold_usd" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateAutoTopupThresholdUsd() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldAutoTopupThresholdUsd)
	return u
}

// AddAutoTopupThresholdUsd adds v to the "auto_topup_threshold_usd" field.
func (u *TeamMemberUpsert) AddAutoTopupThresholdUsd(v float64) *TeamMemberUpsert {
	u.Add(teammember.FieldAutoTopupThresholdUsd, v)
	return u
}

// ClearAutoTopupThresholdUsd clears the value of the "auto_topup_threshold_usd" field.
func (u *TeamMemberUpsert) ClearAutoTopupThresholdUsd() *TeamMemberUpsert {
	u.SetNull(teammember.FieldAutoTopupThresholdUsd)
	return u
}

// SetAutoTopupTargetUsd sets the "auto_topup_target_usd" field.
func (u *TeamMemberUpsert) SetAutoTopupTargetUsd(v float64) *TeamMemberUpsert {
	u.Set(teammember.FieldAutoTopupTargetUsd, v)
	return u
}

// UpdateAutoTopupTargetUsd sets the "auto_topup_target_usd" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateAutoTopupTargetUsd() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldAutoTopupTargetUsd)
	return u
}

// AddAutoTopupTargetUsd adds v to the "auto_topup_target_usd" field.
func (u *TeamMemberUpsert) AddAutoTopupTargetUsd(v float64) *TeamMemberUpsert {
	u.Add(teammember.FieldAutoTopupTargetUsd, v)
	return u
}

// ClearAutoTopupTargetUsd clears the value of the "auto_topup_target_usd" field.
func (u *TeamMemberUpsert) ClearAutoTopupTargetUsd() *TeamMemberUpsert {
	u.SetNull(teammember.FieldAutoTopupTargetUsd)
	return u
}

// SetGrantedNetUsd sets the "granted_net_usd" field.
func (u *TeamMemberUpsert) SetGrantedNetUsd(v float64) *TeamMemberUpsert {
	u.Set(teammember.FieldGrantedNetUsd, v)
	return u
}

// UpdateGrantedNetUsd sets the "granted_net_usd" field to the value that was provided on create.
func (u *TeamMemberUpsert) UpdateGrantedNetUsd() *TeamMemberUpsert {
	u.SetExcluded(teammember.FieldGrantedNetUsd)
	return u
}

// AddGrantedNetUsd adds v to the "granted_net_usd" field.
func (u *TeamMemberUpsert) AddGrantedNetUsd(v float64) *TeamMemberUpsert {
	u.Add(teammember.FieldGrantedNetUsd, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamMemberUpsertOne) UpdateNewValues() *TeamMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(teammember.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamMemberUpsertOne) Ignore() *TeamMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamMemberUpsertOne) DoNothing() *TeamMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamMemberCreate.OnConflict
// documentation for more info.
func (u *TeamMemberUpsertOne) Update(set func(*TeamMemberUpsert)) *TeamMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamMemberUpsertOne) SetUpdatedAt(v time.Time) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateUpdatedAt() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *TeamMemberUpsertOne) SetOwnerUserID(v int64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *TeamMemberUpsertOne) AddOwnerUserID(v int64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateOwnerUserID() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetMemberUserID sets the "member_user_id" field.
func (u *TeamMemberUpsertOne) SetMemberUserID(v int64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetMemberUserID(v)
	})
}

// AddMemberUserID adds v to the "member_user_id" field.
func (u *TeamMemberUpsertOne) AddMemberUserID(v int64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddMemberUserID(v)
	})
}

// UpdateMemberUserID sets the "member_user_id" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateMemberUserID() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateMemberUserID()
	})
}

// SetRole sets the "role" field.
func (u *TeamMemberUpsertOne) SetRole(v string) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateRole() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateRole()
	})
}

// SetStatus sets the "status" field.
func (u *TeamMemberUpsertOne) SetStatus(v string) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateStatus() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateStatus()
	})
}

// SetDepartmentID sets the "department_id" field.
func (u *TeamMemberUpsertOne) SetDepartmentID(v int64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetDepartmentID(v)
	})
}

// AddDepartmentID adds v to the "department_id" field.
func (u *TeamMemberUpsertOne) AddDepartmentID(v int64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddDepartmentID(v)
	})
}

// UpdateDepartmentID sets the "department_id" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateDepartmentID() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateDepartmentID()
	})
}

// ClearDepartmentID clears the value of the "department_id" field.
func (u *TeamMemberUpsertOne) ClearDepartmentID() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.ClearDepartmentID()
	})
}

// SetQuotaMode sets the "quota_mode" field.
func (u *TeamMemberUpsertOne) SetQuotaMode(v string) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetQuotaMode(v)
	})
}

// UpdateQuotaMode sets the "quota_mode" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateQuotaMode() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateQuotaMode()
	})
}

// SetAutoTopupThresholdUsd sets the "auto_topup_threshold_usd" field.
func (u *TeamMemberUpsertOne) SetAutoTopupThresholdUsd(v float64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetAutoTopupThresholdUsd(v)
	})
}

// AddAutoTopupThresholdUsd adds v to the "auto_topup_threshold_usd" field.
func (u *TeamMemberUpsertOne) AddAutoTopupThresholdUsd(v float64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddAutoTopupThresholdUsd(v)
	})
}

// UpdateAutoTopupThresholdUsd sets the "auto_topup_threshold_usd" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateAutoTopupThresholdUsd() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateAutoTopupThresholdUsd()
	})
}

// ClearAutoTopupThresholdUsd clears the value of the "auto_topup_threshold_usd" field.
func (u *TeamMemberUpsertOne) ClearAutoTopupThresholdUsd() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.ClearAutoTopupThresholdUsd()
	})
}

// SetAutoTopupTargetUsd sets the "auto_topup_target_usd" field.
func (u *TeamMemberUpsertOne) SetAutoTopupTargetUsd(v float64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetAutoTopupTargetUsd(v)
	})
}

// AddAutoTopupTargetUsd adds v to the "auto_topup_target_usd" field.
func (u *TeamMemberUpsertOne) AddAutoTopupTargetUsd(v float64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddAutoTopupTargetUsd(v)
	})
}

// UpdateAutoTopupTargetUsd sets the "auto_topup_target_usd" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateAutoTopupTargetUsd() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateAutoTopupTargetUsd()
	})
}

// ClearAutoTopupTargetUsd clears the value of the "auto_topup_target_usd" field.
func (u *TeamMemberUpsertOne) ClearAutoTopupTargetUsd() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.ClearAutoTopupTargetUsd()
	})
}

// SetGrantedNetUsd sets the "granted_net_usd" field.
func (u *TeamMemberUpsertOne) SetGrantedNetUsd(v float64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetGrantedNetUsd(v)
	})
}

// AddGrantedNetUsd adds v to the "granted_net_usd" field.
func (u *TeamMemberUpsertOne) AddGrantedNetUsd(v float64) *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddGrantedNetUsd(v)
	})
}

// UpdateGrantedNetUsd sets the "granted_net_usd" field to the value that was provided on create.
func (u *TeamMemberUpsertOne) UpdateGrantedNetUsd() *TeamMemberUpsertOne {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateGrantedNetUsd()
	})
}

// Exec executes the query.
func (u *TeamMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamMemberUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamMemberUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamMemberCreateBulk is the builder for creating many TeamMember entities in bulk.
type TeamMemberCreateBulk struct {
	config
	err      error
	builders []*TeamMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamMember entities in the database.
func (_c *TeamMemberCreateBulk) Save(ctx context.Context) ([]*TeamMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamMemberCreateBulk) SaveX(ctx context.Context) []*TeamMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamMemberUpsertBulk {
	_c.conflict = opts
	return &TeamMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamMemberCreateBulk) OnConflictColumns(columns ...string) *TeamMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamMemberUpsertBulk{
		create: _c,
	}
}

// TeamMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamMember nodes.
type TeamMemberUpsertBulk struct {
	create *TeamMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamMemberUpsertBulk) UpdateNewValues() *TeamMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(teammember.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamMemberUpsertBulk) Ignore() *TeamMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamMemberUpsertBulk) DoNothing() *TeamMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamMemberCreateBulk.OnConflict
// documentation for more info.
func (u *TeamMemberUpsertBulk) Update(set func(*TeamMemberUpsert)) *TeamMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamMemberUpsertBulk) SetUpdatedAt(v time.Time) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateUpdatedAt() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *TeamMemberUpsertBulk) SetOwnerUserID(v int64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *TeamMemberUpsertBulk) AddOwnerUserID(v int64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateOwnerUserID() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetMemberUserID sets the "member_user_id" field.
func (u *TeamMemberUpsertBulk) SetMemberUserID(v int64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetMemberUserID(v)
	})
}

// AddMemberUserID adds v to the "member_user_id" field.
func (u *TeamMemberUpsertBulk) AddMemberUserID(v int64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddMemberUserID(v)
	})
}

// UpdateMemberUserID sets the "member_user_id" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateMemberUserID() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateMemberUserID()
	})
}

// SetRole sets the "role" field.
func (u *TeamMemberUpsertBulk) SetRole(v string) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateRole() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateRole()
	})
}

// SetStatus sets the "status" field.
func (u *TeamMemberUpsertBulk) SetStatus(v string) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateStatus() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateStatus()
	})
}

// SetDepartmentID sets the "department_id" field.
func (u *TeamMemberUpsertBulk) SetDepartmentID(v int64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetDepartmentID(v)
	})
}

// AddDepartmentID adds v to the "department_id" field.
func (u *TeamMemberUpsertBulk) AddDepartmentID(v int64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddDepartmentID(v)
	})
}

// UpdateDepartmentID sets the "department_id" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateDepartmentID() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateDepartmentID()
	})
}

// ClearDepartmentID clears the value of the "department_id" field.
func (u *TeamMemberUpsertBulk) ClearDepartmentID() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.ClearDepartmentID()
	})
}

// SetQuotaMode sets the "quota_mode" field.
func (u *TeamMemberUpsertBulk) SetQuotaMode(v string) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetQuotaMode(v)
	})
}

// UpdateQuotaMode sets the "quota_mode" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateQuotaMode() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateQuotaMode()
	})
}

// SetAutoTopupThresholdUsd sets the "auto_topup_threshold_usd" field.
func (u *TeamMemberUpsertBulk) SetAutoTopupThresholdUsd(v float64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetAutoTopupThresholdUsd(v)
	})
}

// AddAutoTopupThresholdUsd adds v to the "auto_topup_threshold_usd" field.
func (u *TeamMemberUpsertBulk) AddAutoTopupThresholdUsd(v float64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddAutoTopupThresholdUsd(v)
	})
}

// UpdateAutoTopupThresholdUsd sets the "auto_topup_threshold_usd" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateAutoTopupThresholdUsd() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateAutoTopupThresholdUsd()
	})
}

// ClearAutoTopupThresholdUsd clears the value of the "auto_topup_threshold_usd" field.
func (u *TeamMemberUpsertBulk) ClearAutoTopupThresholdUsd() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.ClearAutoTopupThresholdUsd()
	})
}

// SetAutoTopupTargetUsd sets the "auto_topup_target_usd" field.
func (u *TeamMemberUpsertBulk) SetAutoTopupTargetUsd(v float64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetAutoTopupTargetUsd(v)
	})
}

// AddAutoTopupTargetUsd adds v to the "auto_topup_target_usd" field.
func (u *TeamMemberUpsertBulk) AddAutoTopupTargetUsd(v float64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddAutoTopupTargetUsd(v)
	})
}

// UpdateAutoTopupTargetUsd sets the "auto_topup_target_usd" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateAutoTopupTargetUsd() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateAutoTopupTargetUsd()
	})
}

// ClearAutoTopupTargetUsd clears the value of the "auto_topup_target_usd" field.
func (u *TeamMemberUpsertBulk) ClearAutoTopupTargetUsd() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.ClearAutoTopupTargetUsd()
	})
}

// SetGrantedNetUsd sets the "granted_net_usd" field.
func (u *TeamMemberUpsertBulk) SetGrantedNetUsd(v float64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.SetGrantedNetUsd(v)
	})
}

// AddGrantedNetUsd adds v to the "granted_net_usd" field.
func (u *TeamMemberUpsertBulk) AddGrantedNetUsd(v float64) *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.AddGrantedNetUsd(v)
	})
}

// UpdateGrantedNetUsd sets the "granted_net_usd" field to the value that was provided on create.
func (u *TeamMemberUpsertBulk) UpdateGrantedNetUsd() *TeamMemberUpsertBulk {
	return u.Update(func(s *TeamMemberUpsert) {
		s.UpdateGrantedNetUsd()
	})
}

// Exec executes the query.
func (u *TeamMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
