// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/teamactivitylog"
)

// TeamActivityLogUpdate is the builder for updating TeamActivityLog entities.
type TeamActivityLogUpdate struct {
	config
	hooks    []Hook
	mutation *TeamActivityLogMutation
}

// Where appends a list predicates to the TeamActivityLogUpdate builder.
func (_u *TeamActivityLogUpdate) Where(ps ...predicate.TeamActivityLog) *TeamActivityLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *TeamActivityLogUpdate) SetOwnerUserID(v int64) *TeamActivityLogUpdate {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *TeamActivityLogUpdate) SetNillableOwnerUserID(v *int64) *TeamActivityLogUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *TeamActivityLogUpdate) AddOwnerUserID(v int64) *TeamActivityLogUpdate {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *TeamActivityLogUpdate) SetActorUserID(v int64) *TeamActivityLogUpdate {
	_u.mutation.ResetActorUserID()
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *TeamActivityLogUpdate) SetNillableActorUserID(v *int64) *TeamActivityLogUpdate {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// AddActorUserID adds value to the "actor_user_id" field.
func (_u *TeamActivityLogUpdate) AddActorUserID(v int64) *TeamActivityLogUpdate {
	_u.mutation.AddActorUserID(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *TeamActivityLogUpdate) SetAction(v string) *TeamActivityLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *TeamActivityLogUpdate) SetNillableAction(v *string) *TeamActivityLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *TeamActivityLogUpdate) SetDetail(v string) *TeamActivityLogUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *TeamActivityLogUpdate) SetNillableDetail(v *string) *TeamActivityLogUpdate {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// Mutation returns the TeamActivityLogMutation object of the builder.
func (_u *TeamActivityLogUpdate) Mutation() *TeamActivityLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamActivityLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamActivityLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamActivityLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamActivityLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamActivityLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := teamactivitylog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TeamActivityLog.action": %w`, err)}
		}
	}
	return nil
}

func (_u *TeamActivityLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamactivitylog.Table, teamactivitylog.Columns, sqlgraph.NewFieldSpec(teamactivitylog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(teamactivitylog.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(teamactivitylog.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActorUserID(); ok {
		_spec.SetField(teamactivitylog.FieldActorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorUserID(); ok {
		_spec.AddField(teamactivitylog.FieldActorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(teamactivitylog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(teamactivitylog.FieldDetail, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamactivitylog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamActivityLogUpdateOne is the builder for updating a single TeamActivityLog entity.
type TeamActivityLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamActivityLogMutation
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *TeamActivityLogUpdateOne) SetOwnerUserID(v int64) *TeamActivityLogUpdateOne {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *TeamActivityLogUpdateOne) SetNillableOwnerUserID(v *int64) *TeamActivityLogUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *TeamActivityLogUpdateOne) AddOwnerUserID(v int64) *TeamActivityLogUpdateOne {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *TeamActivityLogUpdateOne) SetActorUserID(v int64) *TeamActivityLogUpdateOne {
	_u.mutation.ResetActorUserID()
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *TeamActivityLogUpdateOne) SetNillableActorUserID(v *int64) *TeamActivityLogUpdateOne {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// AddActorUserID adds value to the "actor_user_id" field.
func (_u *TeamActivityLogUpdateOne) AddActorUserID(v int64) *TeamActivityLogUpdateOne {
	_u.mutation.AddActorUserID(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *TeamActivityLogUpdateOne) SetAction(v string) *TeamActivityLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *TeamActivityLogUpdateOne) SetNillableAction(v *string) *TeamActivityLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *TeamActivityLogUpdateOne) SetDetail(v string) *TeamActivityLogUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *TeamActivityLogUpdateOne) SetNillableDetail(v *string) *TeamActivityLogUpdateOne {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// Mutation returns the TeamActivityLogMutation object of the builder.
func (_u *TeamActivityLogUpdateOne) Mutation() *TeamActivityLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the TeamActivityLogUpdate builder.
func (_u *TeamActivityLogUpdateOne) Where(ps ...predicate.TeamActivityLog) *TeamActivityLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamActivityLogUpdateOne) Select(field string, fields ...string) *TeamActivityLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamActivityLog entity.
func (_u *TeamActivityLogUpdateOne) Save(ctx context.Context) (*TeamActivityLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamActivityLogUpdateOne) SaveX(ctx context.Context) *TeamActivityLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamActivityLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamActivityLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamActivityLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := teamactivitylog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TeamActivityLog.action": %w`, err)}
		}
	}
	return nil
}

func (_u *TeamActivityLogUpdateOne) sqlSave(ctx context.Context) (_node *TeamActivityLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamactivitylog.Table, teamactivitylog.Columns, sqlgraph.NewFieldSpec(teamactivitylog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamActivityLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamactivitylog.FieldID)
		for _, f := range fields {
			if !teamactivitylog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamactivitylog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(teamactivitylog.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(teamactivitylog.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActorUserID(); ok {
		_spec.SetField(teamactivitylog.FieldActorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorUserID(); ok {
		_spec.AddField(teamactivitylog.FieldActorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(teamactivitylog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(teamactivitylog.FieldDetail, field.TypeString, value)
	}
	_node = &TeamActivityLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamactivitylog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
