// Code generated by ent, DO NOT EDIT.

package modelpricing

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the modelpricing type in the database.
	Label = "model_pricing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldPricingUnit holds the string denoting the pricing_unit field in the database.
	FieldPricingUnit = "pricing_unit"
	// FieldInputCostPerToken holds the string denoting the input_cost_per_token field in the database.
	FieldInputCostPerToken = "input_cost_per_token"
	// FieldOutputCostPerToken holds the string denoting the output_cost_per_token field in the database.
	FieldOutputCostPerToken = "output_cost_per_token"
	// FieldCacheCreationInputTokenCost holds the string denoting the cache_creation_input_token_cost field in the database.
	FieldCacheCreationInputTokenCost = "cache_creation_input_token_cost"
	// FieldCacheReadInputTokenCost holds the string denoting the cache_read_input_token_cost field in the database.
	FieldCacheReadInputTokenCost = "cache_read_input_token_cost"
	// FieldOutputCostPerImage holds the string denoting the output_cost_per_image field in the database.
	FieldOutputCostPerImage = "output_cost_per_image"
	// FieldOutputCostPerImageToken holds the string denoting the output_cost_per_image_token field in the database.
	FieldOutputCostPerImageToken = "output_cost_per_image_token"
	// FieldInputCostPerTokenPriority holds the string denoting the input_cost_per_token_priority field in the database.
	FieldInputCostPerTokenPriority = "input_cost_per_token_priority"
	// FieldOutputCostPerTokenPriority holds the string denoting the output_cost_per_token_priority field in the database.
	FieldOutputCostPerTokenPriority = "output_cost_per_token_priority"
	// FieldCacheReadInputTokenCostPriority holds the string denoting the cache_read_input_token_cost_priority field in the database.
	FieldCacheReadInputTokenCostPriority = "cache_read_input_token_cost_priority"
	// FieldCacheCreation5mTokenCost holds the string denoting the cache_creation_5m_token_cost field in the database.
	FieldCacheCreation5mTokenCost = "cache_creation_5m_token_cost"
	// FieldCacheCreation1hTokenCost holds the string denoting the cache_creation_1h_token_cost field in the database.
	FieldCacheCreation1hTokenCost = "cache_creation_1h_token_cost"
	// FieldSupportsCacheBreakdown holds the string denoting the supports_cache_breakdown field in the database.
	FieldSupportsCacheBreakdown = "supports_cache_breakdown"
	// FieldImageOutputPricePerToken holds the string denoting the image_output_price_per_token field in the database.
	FieldImageOutputPricePerToken = "image_output_price_per_token"
	// FieldLongContextInputTokenThreshold holds the string denoting the long_context_input_token_threshold field in the database.
	FieldLongContextInputTokenThreshold = "long_context_input_token_threshold"
	// FieldLongContextInputCostMultiplier holds the string denoting the long_context_input_cost_multiplier field in the database.
	FieldLongContextInputCostMultiplier = "long_context_input_cost_multiplier"
	// FieldLongContextOutputCostMultiplier holds the string denoting the long_context_output_cost_multiplier field in the database.
	FieldLongContextOutputCostMultiplier = "long_context_output_cost_multiplier"
	// FieldSupportsPromptCaching holds the string denoting the supports_prompt_caching field in the database.
	FieldSupportsPromptCaching = "supports_prompt_caching"
	// FieldCustomInputCost holds the string denoting the custom_input_cost field in the database.
	FieldCustomInputCost = "custom_input_cost"
	// FieldCustomOutputCost holds the string denoting the custom_output_cost field in the database.
	FieldCustomOutputCost = "custom_output_cost"
	// FieldDiscountRate holds the string denoting the discount_rate field in the database.
	FieldDiscountRate = "discount_rate"
	// FieldIsCustom holds the string denoting the is_custom field in the database.
	FieldIsCustom = "is_custom"
	// FieldTierPricing holds the string denoting the tier_pricing field in the database.
	FieldTierPricing = "tier_pricing"
	// FieldIsEnabled holds the string denoting the is_enabled field in the database.
	FieldIsEnabled = "is_enabled"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSourceProvider holds the string denoting the source_provider field in the database.
	FieldSourceProvider = "source_provider"
	// FieldSourceAccountID holds the string denoting the source_account_id field in the database.
	FieldSourceAccountID = "source_account_id"
	// FieldPricingStatus holds the string denoting the pricing_status field in the database.
	FieldPricingStatus = "pricing_status"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the modelpricing in the database.
	Table = "model_pricings"
)

// Columns holds all SQL columns for modelpricing fields.
var Columns = []string{
	FieldID,
	FieldModelID,
	FieldDisplayName,
	FieldDescription,
	FieldProvider,
	FieldMode,
	FieldPricingUnit,
	FieldInputCostPerToken,
	FieldOutputCostPerToken,
	FieldCacheCreationInputTokenCost,
	FieldCacheReadInputTokenCost,
	FieldOutputCostPerImage,
	FieldOutputCostPerImageToken,
	FieldInputCostPerTokenPriority,
	FieldOutputCostPerTokenPriority,
	FieldCacheReadInputTokenCostPriority,
	FieldCacheCreation5mTokenCost,
	FieldCacheCreation1hTokenCost,
	FieldSupportsCacheBreakdown,
	FieldImageOutputPricePerToken,
	FieldLongContextInputTokenThreshold,
	FieldLongContextInputCostMultiplier,
	FieldLongContextOutputCostMultiplier,
	FieldSupportsPromptCaching,
	FieldCustomInputCost,
	FieldCustomOutputCost,
	FieldDiscountRate,
	FieldIsCustom,
	FieldTierPricing,
	FieldIsEnabled,
	FieldSource,
	FieldSourceProvider,
	FieldSourceAccountID,
	FieldPricingStatus,
	FieldLastSyncedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	ModelIDValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// DefaultMode holds the default value on creation for the "mode" field.
	DefaultMode string
	// ModeValidator is a validator for the "mode" field. It is called by the builders before save.
	ModeValidator func(string) error
	// DefaultSupportsCacheBreakdown holds the default value on creation for the "supports_cache_breakdown" field.
	DefaultSupportsCacheBreakdown bool
	// DefaultSupportsPromptCaching holds the default value on creation for the "supports_prompt_caching" field.
	DefaultSupportsPromptCaching bool
	// DefaultIsCustom holds the default value on creation for the "is_custom" field.
	DefaultIsCustom bool
	// DefaultIsEnabled holds the default value on creation for the "is_enabled" field.
	DefaultIsEnabled bool
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultSourceProvider holds the default value on creation for the "source_provider" field.
	DefaultSourceProvider string
	// SourceProviderValidator is a validator for the "source_provider" field. It is called by the builders before save.
	SourceProviderValidator func(string) error
	// DefaultPricingStatus holds the default value on creation for the "pricing_status" field.
	DefaultPricingStatus string
	// PricingStatusValidator is a validator for the "pricing_status" field. It is called by the builders before save.
	PricingStatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// PricingUnit defines the type for the "pricing_unit" enum field.
type PricingUnit string

// PricingUnitToken is the default value of the PricingUnit enum.
const DefaultPricingUnit = PricingUnitToken

// PricingUnit values.
const (
	PricingUnitToken           PricingUnit = "token"
	PricingUnitSecond          PricingUnit = "second"
	PricingUnitImageGeneration PricingUnit = "image_generation"
	PricingUnitVideoGeneration PricingUnit = "video_generation"
)

func (pu PricingUnit) String() string {
	return string(pu)
}

// PricingUnitValidator is a validator for the "pricing_unit" field enum values. It is called by the builders before save.
func PricingUnitValidator(pu PricingUnit) error {
	switch pu {
	case PricingUnitToken, PricingUnitSecond, PricingUnitImageGeneration, PricingUnitVideoGeneration:
		return nil
	default:
		return fmt.Errorf("modelpricing: invalid enum value for pricing_unit field: %q", pu)
	}
}

// OrderOption defines the ordering options for the ModelPricing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByPricingUnit orders the results by the pricing_unit field.
func ByPricingUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricingUnit, opts...).ToFunc()
}

// ByInputCostPerToken orders the results by the input_cost_per_token field.
func ByInputCostPerToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputCostPerToken, opts...).ToFunc()
}

// ByOutputCostPerToken orders the results by the output_cost_per_token field.
func ByOutputCostPerToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputCostPerToken, opts...).ToFunc()
}

// ByCacheCreationInputTokenCost orders the results by the cache_creation_input_token_cost field.
func ByCacheCreationInputTokenCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreationInputTokenCost, opts...).ToFunc()
}

// ByCacheReadInputTokenCost orders the results by the cache_read_input_token_cost field.
func ByCacheReadInputTokenCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadInputTokenCost, opts...).ToFunc()
}

// ByOutputCostPerImage orders the results by the output_cost_per_image field.
func ByOutputCostPerImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputCostPerImage, opts...).ToFunc()
}

// ByOutputCostPerImageToken orders the results by the output_cost_per_image_token field.
func ByOutputCostPerImageToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputCostPerImageToken, opts...).ToFunc()
}

// ByInputCostPerTokenPriority orders the results by the input_cost_per_token_priority field.
func ByInputCostPerTokenPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputCostPerTokenPriority, opts...).ToFunc()
}

// ByOutputCostPerTokenPriority orders the results by the output_cost_per_token_priority field.
func ByOutputCostPerTokenPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputCostPerTokenPriority, opts...).ToFunc()
}

// ByCacheReadInputTokenCostPriority orders the results by the cache_read_input_token_cost_priority field.
func ByCacheReadInputTokenCostPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadInputTokenCostPriority, opts...).ToFunc()
}

// ByCacheCreation5mTokenCost orders the results by the cache_creation_5m_token_cost field.
func ByCacheCreation5mTokenCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreation5mTokenCost, opts...).ToFunc()
}

// ByCacheCreation1hTokenCost orders the results by the cache_creation_1h_token_cost field.
func ByCacheCreation1hTokenCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreation1hTokenCost, opts...).ToFunc()
}

// BySupportsCacheBreakdown orders the results by the supports_cache_breakdown field.
func BySupportsCacheBreakdown(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportsCacheBreakdown, opts...).ToFunc()
}

// ByImageOutputPricePerToken orders the results by the image_output_price_per_token field.
func ByImageOutputPricePerToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageOutputPricePerToken, opts...).ToFunc()
}

// ByLongContextInputTokenThreshold orders the results by the long_context_input_token_threshold field.
func ByLongContextInputTokenThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongContextInputTokenThreshold, opts...).ToFunc()
}

// ByLongContextInputCostMultiplier orders the results by the long_context_input_cost_multiplier field.
func ByLongContextInputCostMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongContextInputCostMultiplier, opts...).ToFunc()
}

// ByLongContextOutputCostMultiplier orders the results by the long_context_output_cost_multiplier field.
func ByLongContextOutputCostMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongContextOutputCostMultiplier, opts...).ToFunc()
}

// BySupportsPromptCaching orders the results by the supports_prompt_caching field.
func BySupportsPromptCaching(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportsPromptCaching, opts...).ToFunc()
}

// ByCustomInputCost orders the results by the custom_input_cost field.
func ByCustomInputCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomInputCost, opts...).ToFunc()
}

// ByCustomOutputCost orders the results by the custom_output_cost field.
func ByCustomOutputCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomOutputCost, opts...).ToFunc()
}

// ByDiscountRate orders the results by the discount_rate field.
func ByDiscountRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountRate, opts...).ToFunc()
}

// ByIsCustom orders the results by the is_custom field.
func ByIsCustom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCustom, opts...).ToFunc()
}

// ByTierPricing orders the results by the tier_pricing field.
func ByTierPricing(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTierPricing, opts...).ToFunc()
}

// ByIsEnabled orders the results by the is_enabled field.
func ByIsEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEnabled, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySourceProvider orders the results by the source_provider field.
func BySourceProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceProvider, opts...).ToFunc()
}

// BySourceAccountID orders the results by the source_account_id field.
func BySourceAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceAccountID, opts...).ToFunc()
}

// ByPricingStatus orders the results by the pricing_status field.
func ByPricingStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricingStatus, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
