// Code generated by ent, DO NOT EDIT.

package endpoint

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldAccountID, v))
}

// StableID applies equality check predicate on the "stable_id" field. It's identical to StableIDEQ.
func StableID(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldStableID, v))
}

// OutboundProtocol applies equality check predicate on the "outbound_protocol" field. It's identical to OutboundProtocolEQ.
func OutboundProtocol(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldOutboundProtocol, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldBaseURL, v))
}

// AuthHeader applies equality check predicate on the "auth_header" field. It's identical to AuthHeaderEQ.
func AuthHeader(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldAuthHeader, v))
}

// AuthScheme applies equality check predicate on the "auth_scheme" field. It's identical to AuthSchemeEQ.
func AuthScheme(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldAuthScheme, v))
}

// ModelsSource applies equality check predicate on the "models_source" field. It's identical to ModelsSourceEQ.
func ModelsSource(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldModelsSource, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldPriority, v))
}

// Health applies equality check predicate on the "health" field. It's identical to HealthEQ.
func Health(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldHealth, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldAccountID, vs...))
}

// StableIDEQ applies the EQ predicate on the "stable_id" field.
func StableIDEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldStableID, v))
}

// StableIDNEQ applies the NEQ predicate on the "stable_id" field.
func StableIDNEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldStableID, v))
}

// StableIDIn applies the In predicate on the "stable_id" field.
func StableIDIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldStableID, vs...))
}

// StableIDNotIn applies the NotIn predicate on the "stable_id" field.
func StableIDNotIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldStableID, vs...))
}

// StableIDGT applies the GT predicate on the "stable_id" field.
func StableIDGT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldStableID, v))
}

// StableIDGTE applies the GTE predicate on the "stable_id" field.
func StableIDGTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldStableID, v))
}

// StableIDLT applies the LT predicate on the "stable_id" field.
func StableIDLT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldStableID, v))
}

// StableIDLTE applies the LTE predicate on the "stable_id" field.
func StableIDLTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldStableID, v))
}

// StableIDContains applies the Contains predicate on the "stable_id" field.
func StableIDContains(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContains(FieldStableID, v))
}

// StableIDHasPrefix applies the HasPrefix predicate on the "stable_id" field.
func StableIDHasPrefix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasPrefix(FieldStableID, v))
}

// StableIDHasSuffix applies the HasSuffix predicate on the "stable_id" field.
func StableIDHasSuffix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasSuffix(FieldStableID, v))
}

// StableIDEqualFold applies the EqualFold predicate on the "stable_id" field.
func StableIDEqualFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEqualFold(FieldStableID, v))
}

// StableIDContainsFold applies the ContainsFold predicate on the "stable_id" field.
func StableIDContainsFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContainsFold(FieldStableID, v))
}

// OutboundProtocolEQ applies the EQ predicate on the "outbound_protocol" field.
func OutboundProtocolEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldOutboundProtocol, v))
}

// OutboundProtocolNEQ applies the NEQ predicate on the "outbound_protocol" field.
func OutboundProtocolNEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldOutboundProtocol, v))
}

// OutboundProtocolIn applies the In predicate on the "outbound_protocol" field.
func OutboundProtocolIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldOutboundProtocol, vs...))
}

// OutboundProtocolNotIn applies the NotIn predicate on the "outbound_protocol" field.
func OutboundProtocolNotIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldOutboundProtocol, vs...))
}

// OutboundProtocolGT applies the GT predicate on the "outbound_protocol" field.
func OutboundProtocolGT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldOutboundProtocol, v))
}

// OutboundProtocolGTE applies the GTE predicate on the "outbound_protocol" field.
func OutboundProtocolGTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldOutboundProtocol, v))
}

// OutboundProtocolLT applies the LT predicate on the "outbound_protocol" field.
func OutboundProtocolLT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldOutboundProtocol, v))
}

// OutboundProtocolLTE applies the LTE predicate on the "outbound_protocol" field.
func OutboundProtocolLTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldOutboundProtocol, v))
}

// OutboundProtocolContains applies the Contains predicate on the "outbound_protocol" field.
func OutboundProtocolContains(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContains(FieldOutboundProtocol, v))
}

// OutboundProtocolHasPrefix applies the HasPrefix predicate on the "outbound_protocol" field.
func OutboundProtocolHasPrefix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasPrefix(FieldOutboundProtocol, v))
}

// OutboundProtocolHasSuffix applies the HasSuffix predicate on the "outbound_protocol" field.
func OutboundProtocolHasSuffix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasSuffix(FieldOutboundProtocol, v))
}

// OutboundProtocolEqualFold applies the EqualFold predicate on the "outbound_protocol" field.
func OutboundProtocolEqualFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEqualFold(FieldOutboundProtocol, v))
}

// OutboundProtocolContainsFold applies the ContainsFold predicate on the "outbound_protocol" field.
func OutboundProtocolContainsFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContainsFold(FieldOutboundProtocol, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContainsFold(FieldBaseURL, v))
}

// AuthHeaderEQ applies the EQ predicate on the "auth_header" field.
func AuthHeaderEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldAuthHeader, v))
}

// AuthHeaderNEQ applies the NEQ predicate on the "auth_header" field.
func AuthHeaderNEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldAuthHeader, v))
}

// AuthHeaderIn applies the In predicate on the "auth_header" field.
func AuthHeaderIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldAuthHeader, vs...))
}

// AuthHeaderNotIn applies the NotIn predicate on the "auth_header" field.
func AuthHeaderNotIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldAuthHeader, vs...))
}

// AuthHeaderGT applies the GT predicate on the "auth_header" field.
func AuthHeaderGT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldAuthHeader, v))
}

// AuthHeaderGTE applies the GTE predicate on the "auth_header" field.
func AuthHeaderGTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldAuthHeader, v))
}

// AuthHeaderLT applies the LT predicate on the "auth_header" field.
func AuthHeaderLT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldAuthHeader, v))
}

// AuthHeaderLTE applies the LTE predicate on the "auth_header" field.
func AuthHeaderLTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldAuthHeader, v))
}

// AuthHeaderContains applies the Contains predicate on the "auth_header" field.
func AuthHeaderContains(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContains(FieldAuthHeader, v))
}

// AuthHeaderHasPrefix applies the HasPrefix predicate on the "auth_header" field.
func AuthHeaderHasPrefix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasPrefix(FieldAuthHeader, v))
}

// AuthHeaderHasSuffix applies the HasSuffix predicate on the "auth_header" field.
func AuthHeaderHasSuffix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasSuffix(FieldAuthHeader, v))
}

// AuthHeaderEqualFold applies the EqualFold predicate on the "auth_header" field.
func AuthHeaderEqualFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEqualFold(FieldAuthHeader, v))
}

// AuthHeaderContainsFold applies the ContainsFold predicate on the "auth_header" field.
func AuthHeaderContainsFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContainsFold(FieldAuthHeader, v))
}

// AuthSchemeEQ applies the EQ predicate on the "auth_scheme" field.
func AuthSchemeEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldAuthScheme, v))
}

// AuthSchemeNEQ applies the NEQ predicate on the "auth_scheme" field.
func AuthSchemeNEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldAuthScheme, v))
}

// AuthSchemeIn applies the In predicate on the "auth_scheme" field.
func AuthSchemeIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldAuthScheme, vs...))
}

// AuthSchemeNotIn applies the NotIn predicate on the "auth_scheme" field.
func AuthSchemeNotIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldAuthScheme, vs...))
}

// AuthSchemeGT applies the GT predicate on the "auth_scheme" field.
func AuthSchemeGT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldAuthScheme, v))
}

// AuthSchemeGTE applies the GTE predicate on the "auth_scheme" field.
func AuthSchemeGTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldAuthScheme, v))
}

// AuthSchemeLT applies the LT predicate on the "auth_scheme" field.
func AuthSchemeLT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldAuthScheme, v))
}

// AuthSchemeLTE applies the LTE predicate on the "auth_scheme" field.
func AuthSchemeLTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldAuthScheme, v))
}

// AuthSchemeContains applies the Contains predicate on the "auth_scheme" field.
func AuthSchemeContains(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContains(FieldAuthScheme, v))
}

// AuthSchemeHasPrefix applies the HasPrefix predicate on the "auth_scheme" field.
func AuthSchemeHasPrefix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasPrefix(FieldAuthScheme, v))
}

// AuthSchemeHasSuffix applies the HasSuffix predicate on the "auth_scheme" field.
func AuthSchemeHasSuffix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasSuffix(FieldAuthScheme, v))
}

// AuthSchemeEqualFold applies the EqualFold predicate on the "auth_scheme" field.
func AuthSchemeEqualFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEqualFold(FieldAuthScheme, v))
}

// AuthSchemeContainsFold applies the ContainsFold predicate on the "auth_scheme" field.
func AuthSchemeContainsFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContainsFold(FieldAuthScheme, v))
}

// ModelsSourceEQ applies the EQ predicate on the "models_source" field.
func ModelsSourceEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldModelsSource, v))
}

// ModelsSourceNEQ applies the NEQ predicate on the "models_source" field.
func ModelsSourceNEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldModelsSource, v))
}

// ModelsSourceIn applies the In predicate on the "models_source" field.
func ModelsSourceIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldModelsSource, vs...))
}

// ModelsSourceNotIn applies the NotIn predicate on the "models_source" field.
func ModelsSourceNotIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldModelsSource, vs...))
}

// ModelsSourceGT applies the GT predicate on the "models_source" field.
func ModelsSourceGT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldModelsSource, v))
}

// ModelsSourceGTE applies the GTE predicate on the "models_source" field.
func ModelsSourceGTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldModelsSource, v))
}

// ModelsSourceLT applies the LT predicate on the "models_source" field.
func ModelsSourceLT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldModelsSource, v))
}

// ModelsSourceLTE applies the LTE predicate on the "models_source" field.
func ModelsSourceLTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldModelsSource, v))
}

// ModelsSourceContains applies the Contains predicate on the "models_source" field.
func ModelsSourceContains(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContains(FieldModelsSource, v))
}

// ModelsSourceHasPrefix applies the HasPrefix predicate on the "models_source" field.
func ModelsSourceHasPrefix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasPrefix(FieldModelsSource, v))
}

// ModelsSourceHasSuffix applies the HasSuffix predicate on the "models_source" field.
func ModelsSourceHasSuffix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasSuffix(FieldModelsSource, v))
}

// ModelsSourceEqualFold applies the EqualFold predicate on the "models_source" field.
func ModelsSourceEqualFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEqualFold(FieldModelsSource, v))
}

// ModelsSourceContainsFold applies the ContainsFold predicate on the "models_source" field.
func ModelsSourceContainsFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContainsFold(FieldModelsSource, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldPriority, v))
}

// HealthEQ applies the EQ predicate on the "health" field.
func HealthEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldHealth, v))
}

// HealthNEQ applies the NEQ predicate on the "health" field.
func HealthNEQ(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldHealth, v))
}

// HealthIn applies the In predicate on the "health" field.
func HealthIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldHealth, vs...))
}

// HealthNotIn applies the NotIn predicate on the "health" field.
func HealthNotIn(vs ...string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldHealth, vs...))
}

// HealthGT applies the GT predicate on the "health" field.
func HealthGT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldHealth, v))
}

// HealthGTE applies the GTE predicate on the "health" field.
func HealthGTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldHealth, v))
}

// HealthLT applies the LT predicate on the "health" field.
func HealthLT(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldHealth, v))
}

// HealthLTE applies the LTE predicate on the "health" field.
func HealthLTE(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldHealth, v))
}

// HealthContains applies the Contains predicate on the "health" field.
func HealthContains(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContains(FieldHealth, v))
}

// HealthHasPrefix applies the HasPrefix predicate on the "health" field.
func HealthHasPrefix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasPrefix(FieldHealth, v))
}

// HealthHasSuffix applies the HasSuffix predicate on the "health" field.
func HealthHasSuffix(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldHasSuffix(FieldHealth, v))
}

// HealthEqualFold applies the EqualFold predicate on the "health" field.
func HealthEqualFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEqualFold(FieldHealth, v))
}

// HealthContainsFold applies the ContainsFold predicate on the "health" field.
func HealthContainsFold(v string) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldContainsFold(FieldHealth, v))
}

// CapabilitiesIsNil applies the IsNil predicate on the "capabilities" field.
func CapabilitiesIsNil() predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIsNull(FieldCapabilities))
}

// CapabilitiesNotNil applies the NotNil predicate on the "capabilities" field.
func CapabilitiesNotNil() predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotNull(FieldCapabilities))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Endpoint {
	return predicate.Endpoint(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.Endpoint {
	return predicate.Endpoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.Endpoint {
	return predicate.Endpoint(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Endpoint) predicate.Endpoint {
	return predicate.Endpoint(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Endpoint) predicate.Endpoint {
	return predicate.Endpoint(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Endpoint) predicate.Endpoint {
	return predicate.Endpoint(sql.NotPredicates(p))
}
