// Code generated by ent, DO NOT EDIT.

package teamfundtransfer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLTE(FieldID, id))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldOwnerUserID, v))
}

// MemberUserID applies equality check predicate on the "member_user_id" field. It's identical to MemberUserIDEQ.
func MemberUserID(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldMemberUserID, v))
}

// Direction applies equality check predicate on the "direction" field. It's identical to DirectionEQ.
func Direction(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldDirection, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldAmount, v))
}

// OperatorUserID applies equality check predicate on the "operator_user_id" field. It's identical to OperatorUserIDEQ.
func OperatorUserID(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldOperatorUserID, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldCreatedAt, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLTE(FieldOwnerUserID, v))
}

// MemberUserIDEQ applies the EQ predicate on the "member_user_id" field.
func MemberUserIDEQ(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldMemberUserID, v))
}

// MemberUserIDNEQ applies the NEQ predicate on the "member_user_id" field.
func MemberUserIDNEQ(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNEQ(FieldMemberUserID, v))
}

// MemberUserIDIn applies the In predicate on the "member_user_id" field.
func MemberUserIDIn(vs ...int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldIn(FieldMemberUserID, vs...))
}

// MemberUserIDNotIn applies the NotIn predicate on the "member_user_id" field.
func MemberUserIDNotIn(vs ...int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNotIn(FieldMemberUserID, vs...))
}

// MemberUserIDGT applies the GT predicate on the "member_user_id" field.
func MemberUserIDGT(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGT(FieldMemberUserID, v))
}

// MemberUserIDGTE applies the GTE predicate on the "member_user_id" field.
func MemberUserIDGTE(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGTE(FieldMemberUserID, v))
}

// MemberUserIDLT applies the LT predicate on the "member_user_id" field.
func MemberUserIDLT(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLT(FieldMemberUserID, v))
}

// MemberUserIDLTE applies the LTE predicate on the "member_user_id" field.
func MemberUserIDLTE(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLTE(FieldMemberUserID, v))
}

// DirectionEQ applies the EQ predicate on the "direction" field.
func DirectionEQ(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldDirection, v))
}

// DirectionNEQ applies the NEQ predicate on the "direction" field.
func DirectionNEQ(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNEQ(FieldDirection, v))
}

// DirectionIn applies the In predicate on the "direction" field.
func DirectionIn(vs ...string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldIn(FieldDirection, vs...))
}

// DirectionNotIn applies the NotIn predicate on the "direction" field.
func DirectionNotIn(vs ...string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNotIn(FieldDirection, vs...))
}

// DirectionGT applies the GT predicate on the "direction" field.
func DirectionGT(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGT(FieldDirection, v))
}

// DirectionGTE applies the GTE predicate on the "direction" field.
func DirectionGTE(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGTE(FieldDirection, v))
}

// DirectionLT applies the LT predicate on the "direction" field.
func DirectionLT(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLT(FieldDirection, v))
}

// DirectionLTE applies the LTE predicate on the "direction" field.
func DirectionLTE(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLTE(FieldDirection, v))
}

// DirectionContains applies the Contains predicate on the "direction" field.
func DirectionContains(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldContains(FieldDirection, v))
}

// DirectionHasPrefix applies the HasPrefix predicate on the "direction" field.
func DirectionHasPrefix(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldHasPrefix(FieldDirection, v))
}

// DirectionHasSuffix applies the HasSuffix predicate on the "direction" field.
func DirectionHasSuffix(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldHasSuffix(FieldDirection, v))
}

// DirectionEqualFold applies the EqualFold predicate on the "direction" field.
func DirectionEqualFold(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEqualFold(FieldDirection, v))
}

// DirectionContainsFold applies the ContainsFold predicate on the "direction" field.
func DirectionContainsFold(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldContainsFold(FieldDirection, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLTE(FieldAmount, v))
}

// OperatorUserIDEQ applies the EQ predicate on the "operator_user_id" field.
func OperatorUserIDEQ(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldOperatorUserID, v))
}

// OperatorUserIDNEQ applies the NEQ predicate on the "operator_user_id" field.
func OperatorUserIDNEQ(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNEQ(FieldOperatorUserID, v))
}

// OperatorUserIDIn applies the In predicate on the "operator_user_id" field.
func OperatorUserIDIn(vs ...int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDNotIn applies the NotIn predicate on the "operator_user_id" field.
func OperatorUserIDNotIn(vs ...int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNotIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDGT applies the GT predicate on the "operator_user_id" field.
func OperatorUserIDGT(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGT(FieldOperatorUserID, v))
}

// OperatorUserIDGTE applies the GTE predicate on the "operator_user_id" field.
func OperatorUserIDGTE(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGTE(FieldOperatorUserID, v))
}

// OperatorUserIDLT applies the LT predicate on the "operator_user_id" field.
func OperatorUserIDLT(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLT(FieldOperatorUserID, v))
}

// OperatorUserIDLTE applies the LTE predicate on the "operator_user_id" field.
func OperatorUserIDLTE(v int64) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLTE(FieldOperatorUserID, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamFundTransfer) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamFundTransfer) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamFundTransfer) predicate.TeamFundTransfer {
	return predicate.TeamFundTransfer(sql.NotPredicates(p))
}
